# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibm_responses_grpc_def.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ibm_responses_grpc_def.proto',
  package='ibm',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cibm_responses_grpc_def.proto\x12\x03ibm\"\x0e\n\x0c\x45mptyRequest\"J\n\x0f\x41\x64\x64\x43loudRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x12\n\napi_key_id\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\t\".\n\x10\x41\x64\x64\x43loudResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\"3\n\x11GetCloudsResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0e\n\x06\x63louds\x18\x02 \x03(\t\"(\n\x12\x44\x65leteCloudRequest\x12\x12\n\napi_key_id\x18\x02 \x01(\t\"%\n\x13\x44\x65leteCloudResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"0\n\x10ResourceResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\"\x86\x01\n\x0fResourceRequest\x12%\n\x1d\x66ilterable_parent_resource_id\x18\x01 \x01(\t\x12\x12\n\napi_key_id\x18\x02 \x01(\t\x12\x19\n\x11resource_types_in\x18\x03 \x03(\t\x12\x1d\n\x15resource_types_not_in\x18\x04 \x03(\t2\x8e\x02\n\x10IBMResponseCalls\x12:\n\tadd_cloud\x12\x14.ibm.AddCloudRequest\x1a\x15.ibm.AddCloudResponse\"\x00\x12\x43\n\x0c\x64\x65lete_cloud\x12\x17.ibm.DeleteCloudRequest\x1a\x18.ibm.DeleteCloudResponse\"\x00\x12\x39\n\nget_clouds\x12\x11.ibm.EmptyRequest\x1a\x16.ibm.GetCloudsResponse\"\x00\x12>\n\rget_resources\x12\x14.ibm.ResourceRequest\x1a\x15.ibm.ResourceResponse\"\x00\x62\x06proto3'
)




_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='ibm.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=51,
)


_ADDCLOUDREQUEST = _descriptor.Descriptor(
  name='AddCloudRequest',
  full_name='ibm.AddCloudRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='api_key', full_name='ibm.AddCloudRequest.api_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api_key_id', full_name='ibm.AddCloudRequest.api_key_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='ibm.AddCloudRequest.account_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=127,
)


_ADDCLOUDRESPONSE = _descriptor.Descriptor(
  name='AddCloudResponse',
  full_name='ibm.AddCloudResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ibm.AddCloudResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='ibm.AddCloudResponse.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=175,
)


_GETCLOUDSRESPONSE = _descriptor.Descriptor(
  name='GetCloudsResponse',
  full_name='ibm.GetCloudsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ibm.GetCloudsResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clouds', full_name='ibm.GetCloudsResponse.clouds', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=228,
)


_DELETECLOUDREQUEST = _descriptor.Descriptor(
  name='DeleteCloudRequest',
  full_name='ibm.DeleteCloudRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='api_key_id', full_name='ibm.DeleteCloudRequest.api_key_id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=270,
)


_DELETECLOUDRESPONSE = _descriptor.Descriptor(
  name='DeleteCloudResponse',
  full_name='ibm.DeleteCloudResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ibm.DeleteCloudResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=309,
)


_RESOURCERESPONSE = _descriptor.Descriptor(
  name='ResourceResponse',
  full_name='ibm.ResourceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ibm.ResourceResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='ibm.ResourceResponse.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=359,
)


_RESOURCEREQUEST = _descriptor.Descriptor(
  name='ResourceRequest',
  full_name='ibm.ResourceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filterable_parent_resource_id', full_name='ibm.ResourceRequest.filterable_parent_resource_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api_key_id', full_name='ibm.ResourceRequest.api_key_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource_types_in', full_name='ibm.ResourceRequest.resource_types_in', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource_types_not_in', full_name='ibm.ResourceRequest.resource_types_not_in', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=496,
)

DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['AddCloudRequest'] = _ADDCLOUDREQUEST
DESCRIPTOR.message_types_by_name['AddCloudResponse'] = _ADDCLOUDRESPONSE
DESCRIPTOR.message_types_by_name['GetCloudsResponse'] = _GETCLOUDSRESPONSE
DESCRIPTOR.message_types_by_name['DeleteCloudRequest'] = _DELETECLOUDREQUEST
DESCRIPTOR.message_types_by_name['DeleteCloudResponse'] = _DELETECLOUDRESPONSE
DESCRIPTOR.message_types_by_name['ResourceResponse'] = _RESOURCERESPONSE
DESCRIPTOR.message_types_by_name['ResourceRequest'] = _RESOURCEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREQUEST,
  '__module__' : 'ibm_responses_grpc_def_pb2'
  # @@protoc_insertion_point(class_scope:ibm.EmptyRequest)
  })
_sym_db.RegisterMessage(EmptyRequest)

AddCloudRequest = _reflection.GeneratedProtocolMessageType('AddCloudRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDCLOUDREQUEST,
  '__module__' : 'ibm_responses_grpc_def_pb2'
  # @@protoc_insertion_point(class_scope:ibm.AddCloudRequest)
  })
_sym_db.RegisterMessage(AddCloudRequest)

AddCloudResponse = _reflection.GeneratedProtocolMessageType('AddCloudResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDCLOUDRESPONSE,
  '__module__' : 'ibm_responses_grpc_def_pb2'
  # @@protoc_insertion_point(class_scope:ibm.AddCloudResponse)
  })
_sym_db.RegisterMessage(AddCloudResponse)

GetCloudsResponse = _reflection.GeneratedProtocolMessageType('GetCloudsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCLOUDSRESPONSE,
  '__module__' : 'ibm_responses_grpc_def_pb2'
  # @@protoc_insertion_point(class_scope:ibm.GetCloudsResponse)
  })
_sym_db.RegisterMessage(GetCloudsResponse)

DeleteCloudRequest = _reflection.GeneratedProtocolMessageType('DeleteCloudRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETECLOUDREQUEST,
  '__module__' : 'ibm_responses_grpc_def_pb2'
  # @@protoc_insertion_point(class_scope:ibm.DeleteCloudRequest)
  })
_sym_db.RegisterMessage(DeleteCloudRequest)

DeleteCloudResponse = _reflection.GeneratedProtocolMessageType('DeleteCloudResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETECLOUDRESPONSE,
  '__module__' : 'ibm_responses_grpc_def_pb2'
  # @@protoc_insertion_point(class_scope:ibm.DeleteCloudResponse)
  })
_sym_db.RegisterMessage(DeleteCloudResponse)

ResourceResponse = _reflection.GeneratedProtocolMessageType('ResourceResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCERESPONSE,
  '__module__' : 'ibm_responses_grpc_def_pb2'
  # @@protoc_insertion_point(class_scope:ibm.ResourceResponse)
  })
_sym_db.RegisterMessage(ResourceResponse)

ResourceRequest = _reflection.GeneratedProtocolMessageType('ResourceRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEREQUEST,
  '__module__' : 'ibm_responses_grpc_def_pb2'
  # @@protoc_insertion_point(class_scope:ibm.ResourceRequest)
  })
_sym_db.RegisterMessage(ResourceRequest)



_IBMRESPONSECALLS = _descriptor.ServiceDescriptor(
  name='IBMResponseCalls',
  full_name='ibm.IBMResponseCalls',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=499,
  serialized_end=769,
  methods=[
  _descriptor.MethodDescriptor(
    name='add_cloud',
    full_name='ibm.IBMResponseCalls.add_cloud',
    index=0,
    containing_service=None,
    input_type=_ADDCLOUDREQUEST,
    output_type=_ADDCLOUDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete_cloud',
    full_name='ibm.IBMResponseCalls.delete_cloud',
    index=1,
    containing_service=None,
    input_type=_DELETECLOUDREQUEST,
    output_type=_DELETECLOUDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_clouds',
    full_name='ibm.IBMResponseCalls.get_clouds',
    index=2,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_GETCLOUDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_resources',
    full_name='ibm.IBMResponseCalls.get_resources',
    index=3,
    containing_service=None,
    input_type=_RESOURCEREQUEST,
    output_type=_RESOURCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IBMRESPONSECALLS)

DESCRIPTOR.services_by_name['IBMResponseCalls'] = _IBMRESPONSECALLS

# @@protoc_insertion_point(module_scope)
