# coding: utf-8

"""
    Consumption

    Keeps track of the different services being utilized by users  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from consumption_client.api_client import ApiClient


class ConsumptionApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_consumption(self, consumption, **kwargs):  # noqa: E501
        """Add consumption details  # noqa: E501

        Add consumption details for a given user  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_consumption(consumption, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Consumption consumption: Consumption to be added (required)
        :return: ConsumptionView
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_consumption_with_http_info(consumption, **kwargs)  # noqa: E501
        else:
            (data) = self.add_consumption_with_http_info(consumption, **kwargs)  # noqa: E501
            return data

    def add_consumption_with_http_info(self, consumption, **kwargs):  # noqa: E501
        """Add consumption details  # noqa: E501

        Add consumption details for a given user  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_consumption_with_http_info(consumption, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Consumption consumption: Consumption to be added (required)
        :return: ConsumptionView
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['consumption']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_consumption" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'consumption' is set
        if self.api_client.client_side_validation and ('consumption' not in params or
                                                       params['consumption'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `consumption` when calling `add_consumption`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'consumption' in params:
            body_params = params['consumption']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearer', 'internal']  # noqa: E501

        return self.api_client.call_api(
            '/consumption', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ConsumptionView',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
