# coding: utf-8

"""
    Subscription-svc

    Manage subscriptions to services offered  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import subscription_client
from subscription_client.api.service_api import ServiceApi  # noqa: E501
from subscription_client.rest import ApiException


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self):
        self.api = subscription_client.api.service_api.ServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_services(self):
        """Test case for get_services

        Get services  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
