# coding: utf-8

"""
    Subscription-svc

    Manage subscriptions to services offered  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import subscription_client
from subscription_client.models.subscription_view import SubscriptionView  # noqa: E501
from subscription_client.rest import ApiException


class TestSubscriptionView(unittest.TestCase):
    """SubscriptionView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionView(self):
        """Test SubscriptionView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = subscription_client.models.subscription_view.SubscriptionView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
