from ibm.models import IBMFloatingIP, IBMInstance, IBMPublicGateway, IBMSecurityGroup, IBMSnapshot, IBMSshKey, \
    IBMSubnet, IBMVpcNetwork, IBMLoadBalancer, IBMInstanceGroup, IBMEndpointGateway, IBMPlacementGroup, IBMVpnGateway

RESOURCE_ID_LESS_RESOURCE_LIST = ["IBMDedicatedHostProfile", "IBMOperatingSystem"]

STATUS_VALID = "VALID"

IBM_TAG_TO_RESOURCE_MAPPER = {
    "vpc": IBMVpcNetwork,
    "instance": IBMInstance,
    "key": IBMSshKey,
    "floating-ip": IBMFloatingIP,
    "subnet": IBMSubnet,
    "snapshot": IBMSnapshot,
    "security-group": IBMSecurityGroup,
    "public-gateway": IBMPublicGateway,
    "load-balancer": IBMLoadBalancer,
    "vpn": IBMVpnGateway,
    "instance-group": IBMInstanceGroup,
    "endpoint-gateway": IBMEndpointGateway,
    "placement-group": IBMPlacementGroup
}

# IBM DISCOVERY CONSTANTS
# cos query param
COS_SERVICE_QUERY_PARAM = "kind:iaas cloud-object-storage"
LANGUAGE = "en-us"

TIME_FORMAT = '%Y-%m-%d %H:%M:%S'

# IBM Regional Resources
IBM_INSTANCES = "IBM_INSTANCES"
IBM_SSH_KEYS = "IBM_SSH_KEYS"
IBM_IMAGES = "IBM_IMAGES"
IBM_VPCS = "IBM_VPCS"
IBM_SUBNETS = "IBM_SUBNETS"
IBM_FLOATING_IPS = "IBM_FLOATING_IPS"
IBM_PUBLIC_GATEWAYS = "IBM_PUBLIC_GATEWAYS"
IBM_NETWORK_ACLS = "IBM_NETWORK_ACLS"
IBM_SECURITY_GROUPS = "IBM_SECURITY_GROUPS"
IBM_VPN_GATEWAYS = "IBM_VPN_GATEWAYS"
IBM_IKE_POLICIES = "IBM_IKE_POLICIES"
IBM_IPSEC_POLICIES = "IBM_IPSEC_POLICIES"
IBM_LOAD_BALANCERS = "IBM_LOAD_BALANCERS"
IBM_BLOCK_STORAGE_VOLUMES = "IBM_BLOCK_STORAGE_VOLUMES"
IBM_VOLUME_PROFILES = "IBM_VOLUME_PROFILES"
IBM_INSTANCE_PROFILES = "IBM_INSTANCE_PROFILES"
IBM_OPERATING_SYSTEMS = "IBM_OPERATING_SYSTEMS"
IBM_KUBERNETES_CLUSTERS = "IBM_KUBERNETES_CLUSTERS"
IBM_DEDICATED_HOSTS = "IBM_DEDICATED_HOSTS"
IBM_DEDICATED_HOST_GROUPS = "IBM_DEDICATED_HOST_GROUPS"
IBM_DEDICATED_HOST_PROFILES = "IBM_DEDICATED_HOST_PROFILES"
IBM_PLACEMENT_GROUPS = "IBM_PLACEMENT_GROUPS"
IBM_INSTANCE_GROUPS = "IBM_INSTANCE_GROUPS"
IBM_INSTANCE_TEMPLATES = "IBM_INSTANCE_TEMPLATES"
IBM_ENDPOINT_GATEWAYS = "IBM_ENDPOINT_GATEWAYS"
IBM_SNAPSHOTS = "IBM_SNAPSHOTS"
IBM_LOAD_BALANCER_PROFILES = "IBM_LOAD_BALANCER_PROFILES"
IBM_INSTANCE_INIT_CONFIGS = "IBM_INSTANCE_INIT_CONFIGS"

# IBM Resource Groups
IBM_RESOURCE_GROUPS = "IBM_RESOURCE_GROUPS"

# IBM Global Resources
IBM_GLOBAL_CATALOG = "IBM_GLOBAL_CATALOG"
IBM_RESOURCE_CONTROLLER_CATALOGUE = "IBM_RESOURCE_CONTROLLER_CATALOGUE"
IBM_COST = "IBM_COST"
IBM_TAGS = "IBM_TAGS"
IBM_REGIONS = "IBM_REGIONS"
IBM_SATELLITE_CLUSTERS = "IBM_SATELLITE_CLUSTERS"
IBM_SATELLITE_CLUSTER_KUBE_CONFIG = "IBM_SATELLITE_CLUSTER_KUBE_CONFIG"
IBM_TRANSIT_GATEWAYS = "IBM_TRANSIT_GATEWAYS"
IBM_TRANSIT_GATEWAY_CONNECTIONS = "IBM_TRANSIT_GATEWAY_CONNECTIONS"
# IBM Instances Sub Resources
IBM_INSTANCE_NETWORK_INTERFACES = "IBM_INSTANCE_NETWORK_INTERFACES"
IBM_INSTANCE_VOLUME_ATTACHMENTS = "IBM_INSTANCE_VOLUME_ATTACHMENTS"
IBM_INSTANCE_DISKS = "IBM_INSTANCE_DISKS"

# IBM Instance Network Interface Sub Resource
IBM_INSTANCE_FLOATING_IPS = "IBM_INSTANCE_FLOATING_IPS"

# IBM Vpn Gateway Connection Sub Resources
IBM_VPN_GATEWAY_CONNECTIONS = "IBM_VPN_GATEWAY_CONNECTIONS"

# IBM Vpcs Sub Resources
IBM_VPC_ADDRESS_PREFIXES = "IBM_VPC_ADDRESS_PREFIXES"
IBM_VPC_ROUTING_TABLES = "IBM_VPC_ROUTING_TABLES"

# IBM Routing Table Sub Resources
IBM_VPC_ROUTING_TABLE_ROUTES = "IBM_VPC_ROUTING_TABLE_ROUTES"

# IBM Load Balancer Sub Resources
IBM_LOAD_BALANCER_LISTENERS = "IBM_LOAD_BALANCER_LISTENERS"
IBM_LOAD_BALANCER_POOLS = "IBM_LOAD_BALANCER_POOLS"

# IBM Load Balancer Listener Sub Resources
IBM_LOAD_BALANCER_LISTENER_POLICIES = "IBM_LOAD_BALANCER_LISTENER_POLICIES"

# IBM Load Balancer Pools Sub Resources
IBM_LOAD_BALANCER_POOL_MEMBERS = "IBM_LOAD_BALANCER_POOL_MEMBERS"

# IBM Global Catalog Sub Resources
IBM_COS_ACCESS_KEYS = "IBM_COS_ACCESS_KEYS"
IBM_CLOUD_OBJECT_STORAGES = "IBM_CLOUD_OBJECT_STORAGES"

# IBM Cloud Object Storages Sub Resources
IBM_COS_BUCKETS = "IBM_COS_BUCKETS"

# IBM Kubernetes Cluster Sub Resources
IBM_KUBERNETES_CLUSTER_WORKER_POOLS = "IBM_KUBERNETES_CLUSTER_WORKER_POOLS"

# IBM Dedicated Host Sub Resources
IBM_DEDICATED_HOST_DISKS = "IBM_DEDICATED_HOST_DISKS"

# IBM Instance Group Sub Resources
IBM_INSTANCE_GROUP_MANAGERS = "IBM_INSTANCE_GROUP_MANAGERS"
IBM_INSTANCE_GROUP_MEMBERSHIPS = "IBM_INSTANCE_GROUP_MEMBERSHIPS"

# IBM Instance Group Manager Actions Sub Resources
IBM_INSTANCE_GROUP_MANAGER_ACTIONS = "IBM_INSTANCE_GROUP_MANAGER_ACTIONS"

# IBM Instance Group Manager Policies Sub Resources
IBM_INSTANCE_GROUP_MANAGER_POLICIES = "IBM_INSTANCE_GROUP_MANAGER_POLICIES"

# IBM Subnet Sub Resources
IBM_SUBNET_RESERVED_IPS = "IBM_SUBNET_RESERVED_IPS"

IBM_KUBERNETES_CLUSTERS_BASIC_JSON = "IBM_KUBERNETES_CLUSTERS_BASIC_JSON"
IBM_CLUSTER_KUBE_CONFIG = "IBM_CLUSTER_KUBE_CONFIG"
IBM_CLUSTER_NAMESPACES = "IBM_CLUSTER_NAMESPACES"
IBM_CLUSTER_NAMESPACE_PVCS = "IBM_CLUSTER_NAMESPACE_PVCS"
IBM_CLUSTER_NAMESPACE_PODS = "IBM_CLUSTER_NAMESPACE_PODS"
IBM_CLUSTER_NAMESPACE_SVCS = "IBM_CLUSTER_NAMESPACE_SVCS"
IBM_ZONES = "IBM_ZONES"
VALID = "VALID"
