# coding: utf-8

"""
    Consumption

    Keeps track of the different services being utilized by users  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import consumption_client
from consumption_client.models.consumption import Consumption  # noqa: E501
from consumption_client.rest import ApiException


class TestConsumption(unittest.TestCase):
    """Consumption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsumption(self):
        """Test Consumption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = consumption_client.models.consumption.Consumption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
