# coding: utf-8

"""
    Consumption

    Keeps track of the different services being utilized by users  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import consumption_client
from consumption_client.api.consumption_api import ConsumptionApi  # noqa: E501
from consumption_client.rest import ApiException


class TestConsumptionApi(unittest.TestCase):
    """ConsumptionApi unit test stubs"""

    def setUp(self):
        self.api = consumption_client.api.consumption_api.ConsumptionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_consumption(self):
        """Test case for add_consumption

        Add consumption details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
