"""empty message

Revision ID: 00d2abf81b69
Revises: d5c3d38be02b
Create Date: 2022-09-27 09:19:05.075654

"""

# revision identifiers, used by Alembic.
revision = '00d2abf81b69'
down_revision = 'd5c3d38be02b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_monitoring_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_monitoring_tokens')
    # ### end Alembic commands ###
