"""empty message

Revision ID: 04346b4e6d9f
Revises: 8c224e92c927
Create Date: 2022-02-10 14:02:01.656204

"""

# revision identifiers, used by Alembic.

revision = '04346b4e6d9f'
down_revision = '8c224e92c927'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instance_templates', 'name', existing_type=mysql.VARCHAR(length=64), nullable=False)
    op.alter_column('ibm_network_interface_prototypes', 'allow_ip_spoofing', existing_type=sa.Boolean(),
                    existing_server_default=None, existing_nullable=True, nullable=False, server_default=False)
    op.add_column('ibm_instance_templates', sa.Column('total_volume_bandwidth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instance_templates', 'total_volume_bandwidth')
    op.alter_column('ibm_network_interface_prototypes', 'allow_ip_spoofing', existing_type=sa.Boolean(),
                    existing_nullable=False, nullable=True)
    op.alter_column('ibm_instance_templates', 'name', existing_type=mysql.VARCHAR(length=255), nullable=False)

    # ### end Alembic commands ###
