"""empty message

Revision ID: 05dbc3c1c8c7
Revises: a1e8edf772ed
Create Date: 2023-02-10 09:36:29.784875

"""

# revision identifiers, used by Alembic.
revision = '05dbc3c1c8c7'
down_revision = 'a1e8edf772ed'

from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ttl_intervals', 'vpc_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=True)
    op.drop_constraint('ttl_intervals_ibfk_1', 'ttl_intervals', type_='foreignkey')
    op.create_foreign_key("fk_ttl_intervals_ibm_vpc_networks", 'ttl_intervals', 'ibm_vpc_networks', ['vpc_id'], ['id'],
                          ondelete='CASCADE')
    op.alter_column('workflow_tree_mappings', 'task_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=True)
    op.alter_column('workflow_tree_mappings', 'next_task_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=True)
    op.drop_constraint('workflow_tree_mappings_ibfk_1', 'workflow_tree_mappings', type_='foreignkey')
    op.drop_constraint('workflow_tree_mappings_ibfk_2', 'workflow_tree_mappings', type_='foreignkey')
    op.create_foreign_key("fk_workflow_tree_mappings_workflow_next_tasks", 'workflow_tree_mappings', 'workflow_tasks',
                          ['next_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key("fk_workflow_tree_mappings_workflow_tasks", 'workflow_tree_mappings', 'workflow_tasks',
                          ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workspace_tree_mappings', 'root_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=True)
    op.alter_column('workspace_tree_mappings', 'next_root_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=True)
    op.drop_constraint('workspace_tree_mappings_ibfk_1', 'workspace_tree_mappings', type_='foreignkey')
    op.drop_constraint('workspace_tree_mappings_ibfk_2', 'workspace_tree_mappings', type_='foreignkey')
    op.create_foreign_key("fk_workspace_tree_mappings_workflow_next_roots", 'workspace_tree_mappings', 'workflow_roots',
                          ['next_root_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key("fk_workspace_tree_mappings_workflow_roots", 'workspace_tree_mappings', 'workflow_roots',
                          ['root_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_workspace_tree_mappings_workflow_roots", 'workspace_tree_mappings', type_='foreignkey')
    op.drop_constraint("fk_workspace_tree_mappings_workflow_next_roots", 'workspace_tree_mappings', type_='foreignkey')
    op.create_foreign_key('workspace_tree_mappings_ibfk_2', 'workspace_tree_mappings', 'workflow_roots', ['root_id'],
                          ['id'])
    op.create_foreign_key('workspace_tree_mappings_ibfk_1', 'workspace_tree_mappings', 'workflow_roots',
                          ['next_root_id'], ['id'])
    op.alter_column('workspace_tree_mappings', 'next_root_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=False)
    op.alter_column('workspace_tree_mappings', 'root_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=False)
    op.drop_constraint("fk_workflow_tree_mappings_workflow_tasks", 'workflow_tree_mappings', type_='foreignkey')
    op.drop_constraint("fk_workflow_tree_mappings_workflow_next_tasks", 'workflow_tree_mappings', type_='foreignkey')
    op.create_foreign_key('workflow_tree_mappings_ibfk_2', 'workflow_tree_mappings', 'workflow_tasks', ['task_id'],
                          ['id'])
    op.create_foreign_key('workflow_tree_mappings_ibfk_1', 'workflow_tree_mappings', 'workflow_tasks', ['next_task_id'],
                          ['id'])
    op.alter_column('workflow_tree_mappings', 'next_task_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=False)
    op.alter_column('workflow_tree_mappings', 'task_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=False)
    op.drop_constraint("fk_ttl_intervals_ibm_vpc_networks", 'ttl_intervals', type_='foreignkey')
    op.create_foreign_key('ttl_intervals_ibfk_1', 'ttl_intervals', 'ibm_vpc_networks', ['vpc_id'], ['id'])
    op.alter_column('ttl_intervals', 'vpc_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=False)
    # ### end Alembic commands ###
