"""empty message

Revision ID: 07b4f816a4bd
Revises: 9d4eae8e2a7b
Create Date: 2022-01-26 07:34:18.840996

"""

# revision identifiers, used by Alembic.
revision = '07b4f816a4bd'
down_revision = '9d4eae8e2a7b'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_lb_listener_policy_rules', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_lb_listener_policy_rules', 'status')
    # ### end Alembic commands ###
