"""empty message

Revision ID: 09b647a5b674
Revises: d00ab83f8e71
Create Date: 2021-12-15 09:58:09.265733

"""

# revision identifiers, used by Alembic.
revision = '09b647a5b674'
down_revision = 'd00ab83f8e71'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('uix_ibm_lb_name_vpc_cloud_id_region_id', table_name='ibm_load_balancers')
    op.create_unique_constraint('uix_ibm_lb_name_cloud_id_region_id', 'ibm_load_balancers', ['name', 'cloud_id', 'region_id'])
    op.drop_constraint('ibm_load_balancers_ibfk_5', 'ibm_load_balancers', type_='foreignkey')
    op.drop_column('ibm_load_balancers', 'vpc_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_load_balancers', sa.Column('vpc_id', mysql.VARCHAR(length=32), nullable=False))
    op.create_foreign_key('ibm_load_balancers_ibfk_5', 'ibm_load_balancers', 'ibm_vpc_networks', ['vpc_id'], ['id'])
    op.drop_constraint('uix_ibm_lb_name_cloud_id_region_id', 'ibm_load_balancers', type_='unique')
    op.create_index('uix_ibm_lb_name_vpc_cloud_id_region_id', 'ibm_load_balancers', ['name', 'vpc_id', 'cloud_id', 'region_id'], unique=False)
    # ### end Alembic commands ###