"""empty message

Revision ID: 155b2b56a234
Revises: 7e0d5c2b2863
Create Date: 2022-06-22 22:02:27.739500

"""

# revision identifiers, used by Alembic.
revision = '155b2b56a234'
down_revision = '7e0d5c2b2863'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_clouds', sa.Column('account_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_clouds', 'account_id')
    # ### end Alembic commands ###
