"""empty message

Revision ID: 17cf147063f8
Revises: ae4b032cc160
Create Date: 2022-06-21 12:24:52.937808

"""

# revision identifiers, used by Alembic.
revision = '17cf147063f8'
down_revision = 'ae4b032cc160'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_subnets', 'network_acl_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_subnets', 'network_acl_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###