"""empty message

Revision ID: 18590eb1bd27
Revises: 3def7d0e43e0
Create Date: 2022-01-20 18:11:30.208273

"""

# revision identifiers, used by Alembic.
revision = '18590eb1bd27'
down_revision = '3def7d0e43e0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_ibm_vpn_gateway_member_role_vpn_gateway_id', table_name='ibm_vpn_gateway_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_ibm_vpn_gateway_member_role_vpn_gateway_id', 'ibm_vpn_gateway_members', ['role', 'vpn_gateway_id'], unique=False)
    # ### end Alembic commands ###
