"""empty message

Revision ID: 1c94d3196731
Revises: 04346b4e6d9f
Create Date: 2022-02-12 21:22:35.997521

"""

# revision identifiers, used by Alembic.
revision = '1c94d3196731'
down_revision = '04346b4e6d9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_endpoint_gateways',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('crn', sa.Text(), nullable=False),
    sa.Column('health_state', sa.Enum('ok', 'degraded', 'faulted', 'inapplicable'), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting', 'suspended'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('endpoint_gateway'), nullable=False),
    sa.Column('service_endpoints', sa.JSON(), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_endpoint_gateway_targets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.Enum('provider_infrastructure_service', 'provider_cloud_service'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('crn', sa.Text(), nullable=True),
    sa.Column('endpoint_gateway_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_gateway_id'], ['ibm_endpoint_gateways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_endpoint_gateways_security_groups',
    sa.Column('security_group_id', sa.String(length=32), nullable=False),
    sa.Column('endpoint_gateway_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_gateway_id'], ['ibm_endpoint_gateways.id'], ),
    sa.ForeignKeyConstraint(['security_group_id'], ['ibm_security_groups.id'], ),
    sa.PrimaryKeyConstraint('security_group_id', 'endpoint_gateway_id')
    )
    op.create_table('ibm_subnet_reserved_ips',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=55), nullable=False),
    sa.Column('auto_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.Enum('user', 'provider'), nullable=True),
    sa.Column('resource_type', sa.Enum('subnet_reserved_ip'), nullable=False),
    sa.Column('subnet_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['subnet_id'], ['ibm_subnets.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['ibm_endpoint_gateways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_subnet_reserved_ips')
    op.drop_table('ibm_endpoint_gateways_security_groups')
    op.drop_table('ibm_endpoint_gateway_targets')
    op.drop_table('ibm_endpoint_gateways')
    # ### end Alembic commands ###