"""empty message

Revision ID: 2342618d6c81
Revises: 155b2b56a234
Create Date: 2022-06-23 15:37:32.784772

"""

# revision identifiers, used by Alembic.
revision = '2342618d6c81'
down_revision = '155b2b56a234'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instance_templates', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('ibm_kubernetes_cluster_worker_pools', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('ibm_routing_tables', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('ibm_snapshots', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('ibm_subnet_reserved_ips', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('ibm_volume_attachment_prototypes', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('ibm_volume_attachments', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_volume_attachments', 'status')
    op.drop_column('ibm_volume_attachment_prototypes', 'status')
    op.drop_column('ibm_subnet_reserved_ips', 'status')
    op.drop_column('ibm_snapshots', 'status')
    op.drop_column('ibm_routing_tables', 'status')
    op.drop_column('ibm_kubernetes_cluster_worker_pools', 'status')
    op.drop_column('ibm_instance_templates', 'status')
    # ### end Alembic commands ###