"""empty message

Revision ID: 25c2af580510
Revises: 54b5bbe794e5
Create Date: 2022-06-08 17:01:46.553450

"""

# revision identifiers, used by Alembic.
revision = '25c2af580510'
down_revision = '54b5bbe794e5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_load_balancer_profile_name_cloud_id', 'ibm_load_balancer_profiles', ['name', 'cloud_id'])
    op.drop_constraint('ibm_load_balancer_profiles_ibfk_2', 'ibm_load_balancer_profiles', type_='foreignkey')
    op.drop_column('ibm_load_balancer_profiles', 'region_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_load_balancer_profiles', sa.Column('region_id', mysql.VARCHAR(length=32), nullable=False))
    op.create_foreign_key('ibm_load_balancer_profiles_ibfk_2', 'ibm_load_balancer_profiles', 'ibm_regions', ['region_id'], ['id'])
    op.drop_constraint('uix_load_balancer_profile_name_cloud_id', 'ibm_load_balancer_profiles', type_='unique')
    # ### end Alembic commands ###