"""empty message

Revision ID: 280f15607aad
Revises: d37e222074e9
Create Date: 2023-03-09 15:38:31.421918

"""

# revision identifiers, used by Alembic.
revision = '280f15607aad'
down_revision = 'd37e222074e9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_satellite_clusters', sa.Column('agent_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_satellite_clusters', 'agent_id')
    # ### end Alembic commands ###
