"""empty message

Revision ID: 2c6d529a8ee7
Revises: 759a50e14fbb
Create Date: 2022-07-13 05:24:58.238989

"""

# revision identifiers, used by Alembic.
revision = '2c6d529a8ee7'
down_revision = '49c82b8d2d1b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_resource_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('added', 'deleted', 'updated'), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_resource_logs')
    # ### end Alembic commands ###