"""empty message

Revision ID: 2d2bed26095c
Revises: 475ace644cfb
Create Date: 2022-07-19 07:46:22.718094

"""

# revision identifiers, used by Alembic.
revision = '2d2bed26095c'
down_revision = '475ace644cfb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_resources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('resource_data', sa.JSON(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('cloud_type', sa.Enum('IBM'), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_resources')
    # ### end Alembic commands ###