"""empty message

Revision ID: 316358bf8fb0
Revises: 7c99789944d5
Create Date: 2022-10-31 18:46:38.888180

"""

# revision identifiers, used by Alembic.
revision = '316358bf8fb0'
down_revision = '7c99789944d5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_ibm_resource_group_name_cloud_id', table_name='ibm_resource_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_ibm_resource_group_name_cloud_id', 'ibm_resource_groups', ['name', 'cloud_id'], unique=False)
    # ### end Alembic commands ###
