"""empty message

Revision ID: 3191b5429d81
Revises: d741aeb2fa9f
Create Date: 2021-12-06 08:14:39.610050

"""

# revision identifiers, used by Alembic.
revision = '3191b5429d81'
down_revision = 'd741aeb2fa9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_images', sa.Column('ibm_encryption', sa.Enum('none', 'user_managed'), nullable=False))
    op.add_column('ibm_images', sa.Column('ibm_visible', sa.Enum('public', 'private'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_images', 'ibm_visible')
    op.drop_column('ibm_images', 'ibm_encryption')
    # ### end Alembic commands ###