"""empty message

Revision ID: 3535a742abd6
Revises: 5c8b7b8756af
Create Date: 2022-05-10 13:42:49.697345

"""

# revision identifiers, used by Alembic.
revision = '3535a742abd6'
down_revision = '5c8b7b8756af'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_clouds', sa.Column('metadata', sa.JSON(), nullable=True))
    op.add_column('ibm_clouds', sa.Column('added_in_mangos', sa.Boolean(), nullable=False))
    op.alter_column('ibm_kubernetes_clusters', 'ibm_state',
                    existing_type=sa.Enum('normal', 'deploying', 'deleting', 'deploy_failed', 'pending'),
                    type_=mysql.ENUM('normal', 'deploying', 'deleting', 'deploy_failed', 'pending', 'warning'),
                    )
    op.alter_column('ibm_dedicated_host_profiles', 'family',
                    existing_type=sa.Enum('balanced', 'memory', 'compute'),
                    type_=mysql.ENUM('balanced', 'memory', 'compute', 'high-memory', 'very-high-memory'),
                    existing_nullable=False
                    )
    op.alter_column('ibm_dedicated_host_groups', 'family',
                    existing_type=sa.Enum('balanced', 'memory', 'compute'),
                    type_=mysql.ENUM('balanced', 'memory', 'compute', 'high-memory', 'very-high-memory'),
                    existing_nullable=False
                    )

    op.alter_column('ibm_vpn_gateways', 'mode',
                    existing_type=sa.Enum('route', 'policy'),
                    nullable=True
                    )
    op.alter_column('ibm_listeners', 'provisioning_status',
                    existing_type=sa.Enum('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending',
                                          'update_pending'),
                    type_=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending',
                                     'update_pending', 'error'),
                    )
    op.drop_index('uix_ibm_floating_ip_name_zone_id_cloud_id', table_name='ibm_floating_ips')
    op.create_unique_constraint('uix_ibm_floating_ip_name_resource_id_zone_id_cloud_id', 'ibm_floating_ips',
                                ['name', 'resource_id', 'zone_id', 'cloud_id'])
    op.drop_index('uix_ibm_operation_system_name_region_id_cloud_id', table_name='ibm_operating_systems')
    op.alter_column('ibm_pool_members', 'subnet_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=True)
    op.drop_index('uix_ibm_image_name_region_id_visibility_cloud_id', table_name='ibm_images')
    op.alter_column('ibm_listeners', 'provisioning_status',
                    existing_type=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed',
                                             'maintenance_pending', 'update_pending', 'error'),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_clouds', 'added_in_mangos')
    op.drop_column('ibm_clouds', 'metadata')
    op.alter_column('ibm_kubernetes_clusters', 'ibm_state',
                    existing_type=mysql.ENUM('normal', 'deploying', 'deleting', 'deploy_failed', 'pending', 'warning'),
                    type_=sa.Enum('normal', 'deploying', 'deleting', 'deploy_failed', 'pending'),
                    )
    op.alter_column('ibm_dedicated_host_profiles', 'family',
                    existing_type=mysql.ENUM('balanced', 'memory', 'compute', 'high-memory', 'very-high-memory'),
                    type_=sa.Enum('balanced', 'memory', 'compute'),
                    )
    op.alter_column('ibm_dedicated_host_groups', 'family',
                    existing_type=mysql.ENUM('balanced', 'memory', 'compute', 'high-memory', 'very-high-memory'),
                    type_=sa.Enum('balanced', 'memory', 'compute'),
                    )
    op.alter_column('ibm_vpn_gateways', 'mode',
                    existing_type=sa.Enum('route', 'policy'),
                    nullable=False
                    )
    op.alter_column('ibm_listeners', 'provisioning_status',
                    existing_type=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed',
                                             'maintenance_pending', 'update_pending', 'error'),
                    type_=sa.Enum('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending',
                                  'update_pending'),
                    )
    op.alter_column('ibm_pool_members', 'subnet_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=False)
    op.create_index('uix_ibm_operation_system_name_region_id_cloud_id', 'ibm_operating_systems',
                    ['name', 'region_id', 'cloud_id'], unique=False)
    op.drop_constraint('uix_ibm_floating_ip_name_resource_id_zone_id_cloud_id', 'ibm_floating_ips', type_='unique')
    op.create_index('uix_ibm_floating_ip_name_zone_id_cloud_id', 'ibm_floating_ips', ['name', 'zone_id', 'cloud_id'],
                    unique=False)
    op.alter_column('ibm_listeners', 'provisioning_status',
               existing_type=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending', 'update_pending', 'error'),
               nullable=True)
    op.create_index('uix_ibm_image_name_region_id_visibility_cloud_id', 'ibm_images', ['name', 'cloud_id', 'region_id', 'visibility'], unique=False)
    # ### end Alembic commands ###
