"""empty message

Revision ID: 40afd45bacfa
Revises: 3df536ee4095
Create Date: 2022-09-29 16:41:47.075313

"""

# revision identifiers, used by Alembic.
revision = '40afd45bacfa'
down_revision = '3df536ee4095'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_monitoring_tokens',
                  sa.Column('status', sa.Enum('AUTHENTICATING', 'VALID', 'INVALID'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_monitoring_tokens', 'status')
    # ### end Alembic commands ###
