"""empty message

Revision ID: 44e65514659e
Revises: f43d800444ba
Create Date: 2022-10-12 13:39:55.363681

"""

# revision identifiers, used by Alembic.
revision = '44e65514659e'
down_revision = 'f43d800444ba'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_idle_resources', sa.Column('resource_type', sa.String(length=50), nullable=True))
    op.alter_column('ibm_idle_resources', 'reason',
                    existing_type=sa.String(length=50),
                    type_=sa.String(length=150),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_idle_resources', 'resource_type')
    op.alter_column('ibm_idle_resources', 'reason',
                    existing_type=sa.String(length=150),
                    type_=sa.String(length=50),
                    existing_nullable=False)
    # ### end Alembic commands ###