"""empty message

Revision ID: 4869be72602a
Revises: 53973aa1311f
Create Date: 2021-09-23 22:35:55.308839

"""

# revision identifiers, used by Alembic.
revision = '4869be72602a'
down_revision = '53973aa1311f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_dedicated_host_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('class', sa.String(length=20), nullable=False),
    sa.Column('disks', sa.JSON(), nullable=False),
    sa.Column('family', sa.Enum('balanced', 'memory', 'compute'), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('memory', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('socket_count', sa.JSON(), nullable=False),
    sa.Column('vcpu_architecture', sa.JSON(), nullable=False),
    sa.Column('vcpu_count', sa.JSON(), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', 'cloud_id', name='uix_ibm_dh_profile_name_region_id_cloudid')
    )
    op.create_table('ibm_dedicated_host_groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('class', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('family', sa.Enum('balanced', 'memory', 'compute'), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('dedicated_host_group'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['ibm_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', 'cloud_id', name='uix_ibm_dh_group_name_region_id_cloudid')
    )
    op.create_table('ibm_dh_profile_supported_instance_profiles',
    sa.Column('dh_profile_id', sa.String(length=32), nullable=False),
    sa.Column('instance_profile_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dh_profile_id'], ['ibm_dedicated_host_profiles.id'], ),
    sa.ForeignKeyConstraint(['instance_profile_id'], ['ibm_instance_profiles.id'], ),
    sa.PrimaryKeyConstraint('dh_profile_id', 'instance_profile_id')
    )
    op.create_table('ibm_dedicated_hosts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('available_memory', sa.Integer(), nullable=False),
    sa.Column('available_vcpu', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('instance_placement_enabled', sa.Boolean(), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting', 'suspended'), nullable=False),
    sa.Column('memory', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provisionable', sa.Boolean(), nullable=False),
    sa.Column('resource_type', sa.Enum('dedicated_host'), nullable=False),
    sa.Column('socket_count', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('available', 'degraded', 'migrating', 'unavailable'), nullable=False),
    sa.Column('vcpu', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('dedicated_host_group_id', sa.String(length=32), nullable=True),
    sa.Column('dedicated_host_profile_id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['dedicated_host_group_id'], ['ibm_dedicated_host_groups.id'], ),
    sa.ForeignKeyConstraint(['dedicated_host_profile_id'], ['ibm_dedicated_host_profiles.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['ibm_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', 'cloud_id', name='uix_ibm_dh_name_region_id_cloudid')
    )
    op.create_table('ibm_dh_group_supported_instance_profiles',
    sa.Column('dh_group_id', sa.String(length=32), nullable=False),
    sa.Column('instance_profile_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dh_group_id'], ['ibm_dedicated_host_groups.id'], ),
    sa.ForeignKeyConstraint(['instance_profile_id'], ['ibm_instance_profiles.id'], ),
    sa.PrimaryKeyConstraint('dh_group_id', 'instance_profile_id')
    )
    op.create_table('ibm_dedicated_host_disks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('interface_type', sa.Enum('nvme'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provisionable', sa.Boolean(), nullable=False),
    sa.Column('resource_type', sa.Enum('dedicated_host_disk'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('supported_instance_interface_types', sa.JSON(), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting', 'suspended'), nullable=True),
    sa.Column('dedicated_host_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['dedicated_host_id'], ['ibm_dedicated_hosts.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_dh_supported_instance_profiles',
    sa.Column('dh_id', sa.String(length=32), nullable=False),
    sa.Column('instance_profile_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dh_id'], ['ibm_dedicated_hosts.id'], ),
    sa.ForeignKeyConstraint(['instance_profile_id'], ['ibm_instance_profiles.id'], ),
    sa.PrimaryKeyConstraint('dh_id', 'instance_profile_id')
    )
    op.add_column('ibm_instance_disks', sa.Column('dedicated_host_disk_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('ibm_instance_disks_ibfk_2', 'ibm_instance_disks', 'ibm_dedicated_host_disks', ['dedicated_host_disk_id'], ['id'])
    op.add_column('ibm_instances', sa.Column('pt_dedicated_host_id', sa.String(length=32), nullable=True))
    op.add_column('ibm_instances', sa.Column('pt_dedicated_host_group_id', sa.String(length=32), nullable=True))
    op.add_column('ibm_instances', sa.Column('pt_placement_group_id', sa.String(length=32), nullable=True))
    op.add_column('ibm_instances', sa.Column('dedicated_host_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('ibm_instances_ibfk_8', 'ibm_instances', 'ibm_dedicated_hosts', ['pt_dedicated_host_id'], ['id'])
    op.create_foreign_key('ibm_instances_ibfk_9', 'ibm_instances', 'ibm_dedicated_hosts', ['dedicated_host_id'], ['id'])
    op.create_foreign_key('ibm_instances_ibfk_10', 'ibm_instances', 'ibm_dedicated_host_groups', ['pt_dedicated_host_group_id'], ['id'])
    op.create_foreign_key('ibm_instances_ibfk_11', 'ibm_instances', 'ibm_placement_groups', ['pt_placement_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ibm_instances_ibfk_11', 'ibm_instances', type_='foreignkey')
    op.drop_constraint('ibm_instances_ibfk_10', 'ibm_instances', type_='foreignkey')
    op.drop_constraint('ibm_instances_ibfk_9', 'ibm_instances', type_='foreignkey')
    op.drop_constraint('ibm_instances_ibfk_8', 'ibm_instances', type_='foreignkey')
    op.drop_column('ibm_instances', 'dedicated_host_id')
    op.drop_column('ibm_instances', 'pt_placement_group_id')
    op.drop_column('ibm_instances', 'pt_dedicated_host_group_id')
    op.drop_column('ibm_instances', 'pt_dedicated_host_id')
    op.drop_constraint('ibm_instance_disks_ibfk_2', 'ibm_instance_disks', type_='foreignkey')
    op.drop_column('ibm_instance_disks', 'dedicated_host_disk_id')
    op.drop_table('ibm_dh_supported_instance_profiles')
    op.drop_table('ibm_dedicated_host_disks')
    op.drop_table('ibm_dh_group_supported_instance_profiles')
    op.drop_table('ibm_dedicated_hosts')
    op.drop_table('ibm_dh_profile_supported_instance_profiles')
    op.drop_table('ibm_dedicated_host_groups')
    op.drop_table('ibm_dedicated_host_profiles')
    # ### end Alembic commands ###
