"""empty message

Revision ID: 4963f81101e6
Revises: bf6336472889
Create Date: 2021-09-23 12:42:07.684401

"""

# revision identifiers, used by Alembic.
revision = '4963f81101e6'
down_revision = 'bf6336472889'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_resource_groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cloud_id', name='uix_ibm_resource_group_name_cloud_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_resource_groups')
    # ### end Alembic commands ###