"""empty message

Revision ID: 49c82b8d2d1b
Revises: 2d2bed26095c
Create Date: 2022-08-16 10:26:46.958537

"""

# revision identifiers, used by Alembic.
revision = '49c82b8d2d1b'
down_revision = '2d2bed26095c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_recovery_resource_blueprints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('resource_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disaster_recovery_backups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DELETING', 'SUCCESS'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('backup_metadata', sa.JSON(), nullable=False),
    sa.Column('disaster_recovery_resource_blueprint_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['disaster_recovery_resource_blueprint_id'], ['disaster_recovery_resource_blueprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disaster_recovery_backups')
    op.drop_table('disaster_recovery_resource_blueprints')
    # ### end Alembic commands ###
