"""empty message

Revision ID: 522aae419cfe
Revises: 82b6cb22b479
Create Date: 2023-02-02 17:37:33.012959

"""

# revision identifiers, used by Alembic.
revision = '522aae419cfe'
down_revision = '82b6cb22b479'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_dedicated_hosts', 'status')
    op.alter_column('ibm_dedicated_hosts', 'lifecycle_state',
                    existing_type=mysql.ENUM('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting',
                                             'suspended'),
                    type_=mysql.VARCHAR(length=50),
                    )
    op.alter_column('ibm_dedicated_hosts', 'state',
                    existing_type=mysql.ENUM('deleting', 'failed', 'pending', 'available'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_endpoint_gateways', 'status')
    op.alter_column('ibm_endpoint_gateways', 'lifecycle_state',
                    existing_type=mysql.ENUM('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting',
                                             'suspended'),
                    type_=mysql.VARCHAR(length=50),
                    )
    op.alter_column('ibm_endpoint_gateways', 'health_state',
                    existing_type=mysql.ENUM('ok', 'faulted', 'degraded', 'inapplicable'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_floating_ips', 'ibm_status')
    op.drop_column('ibm_images', 'ibm_status')
    op.drop_column('ibm_instance_group_manager_actions', 'ibm_status')
    op.drop_column('ibm_instance_group_memberships', 'ibm_status')
    op.drop_column('ibm_instance_groups', 'ibm_status')
    op.drop_column('ibm_instances', 'ibm_status')
    op.drop_column('ibm_kubernetes_clusters', 'ibm_state')

    op.drop_column('ibm_load_balancers', 'status')
    op.alter_column('ibm_load_balancers', 'provisioning_status',
                    existing_type=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed',
                                             'maintenance_pending', 'update_pending'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_listeners', 'status')
    op.alter_column('ibm_listeners', 'provisioning_status',
                    existing_type=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed',
                                             'maintenance_pending', 'update_pending', 'error'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_pools', 'status')
    op.alter_column('ibm_pools', 'provisioning_status',
                    existing_type=mysql.ENUM('active','create_pending','delete_pending','failed','maintenance_pending',
                                             'update_pending'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_pool_members', 'status')
    op.alter_column('ibm_pool_members', 'provisioning_status',
                    existing_type=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed',
                                             'maintenance_pending', 'update_pending'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_lb_listener_policies', 'ibm_status')
    op.alter_column('ibm_lb_listener_policies', 'provisioning_status',
                    existing_type=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed',
                                             'maintenance_pending', 'update_pending'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_lb_listener_policy_rules', 'status')
    op.alter_column('ibm_lb_listener_policy_rules', 'provisioning_status',
                    existing_type=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed',
                                             'maintenance_pending', 'update_pending'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_public_gateways', 'ibm_status')

    op.drop_column('ibm_routing_table_routes', 'status')
    op.alter_column('ibm_routing_table_routes', 'lifecycle_state',
                    existing_type=mysql.ENUM('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting',
                                             'suspended'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_routing_tables', 'status')
    op.alter_column('ibm_routing_tables', 'lifecycle_state',
                    existing_type=mysql.ENUM('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting',
                                             'suspended'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_snapshots', 'status')
    op.alter_column('ibm_snapshots', 'lifecycle_state',
                    existing_type=mysql.ENUM('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting',
                                             'suspended'),
                    type_=mysql.VARCHAR(length=50),
                    )

    op.drop_column('ibm_subnets', 'ibm_status')
    op.drop_column('ibm_volume_attachments', 'ibm_status')
    op.drop_column('ibm_volumes', 'ibm_status')
    op.drop_column('ibm_vpc_networks', 'ibm_status')
    op.drop_column('ibm_vpn_connections', 'ibm_status')
    op.drop_column('ibm_vpn_gateways', 'ibm_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_vpn_gateways',
                  sa.Column('ibm_status', mysql.ENUM('available', 'deleting', 'failed', 'pending'), nullable=False))

    op.add_column('ibm_vpn_connections', sa.Column('ibm_status', mysql.ENUM('up', 'down'), nullable=False))

    op.add_column('ibm_vpc_networks',
                  sa.Column('ibm_status', mysql.ENUM('available', 'failed', 'pending', 'deleting'), nullable=False))

    op.add_column('ibm_volumes',
                  sa.Column('ibm_status', mysql.ENUM('available', 'failed', 'pending', 'pending_deletion', 'unusable'),
                            nullable=False))

    op.add_column('ibm_volume_attachments',
                  sa.Column('ibm_status', mysql.ENUM('attached', 'attaching', 'deleting', 'detaching'), nullable=False))

    op.add_column('ibm_subnets',
                  sa.Column('ibm_status', mysql.ENUM('available', 'deleting', 'pending', 'failed'), nullable=False))

    op.add_column('ibm_snapshots', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))

    op.alter_column('ibm_snapshots', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting',
                                     'suspended')
                    )

    op.add_column('ibm_routing_tables', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('ibm_routing_tables', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting',
                                     'suspended')
                    )

    op.add_column('ibm_routing_table_routes', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('ibm_routing_table_routes', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting',
                                     'suspended')
                    )

    op.add_column('ibm_public_gateways',
                  sa.Column('ibm_status', mysql.ENUM('available', 'failed', 'pending', 'deleting'), nullable=False))

    op.alter_column('ibm_lb_listener_policy_rules', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending',
                                     'update_pending')
                    )
    op.add_column('ibm_lb_listener_policy_rules', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))

    op.alter_column('ibm_lb_listener_policies', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending',
                                     'update_pending')
                    )
    op.add_column('ibm_lb_listener_policies', sa.Column('ibm_status', mysql.VARCHAR(length=50), nullable=False))

    op.alter_column('ibm_pool_members', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending',
                                     'update_pending')
                    )
    op.add_column('ibm_pool_members', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))

    op.alter_column('ibm_pools', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('active','create_pending','delete_pending','failed','maintenance_pending',
                                     'update_pending')
                    )
    op.add_column('ibm_pools', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('ibm_listeners', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed',
                                     'maintenance_pending', 'update_pending', 'error')
                    )
    op.add_column('ibm_listeners', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('ibm_load_balancers', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('active', 'create_pending', 'delete_pending', 'failed',
                                     'maintenance_pending', 'update_pending')
                    )
    op.add_column('ibm_load_balancers', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('ibm_kubernetes_clusters', sa.Column('ibm_state',
                                                       mysql.ENUM('normal', 'deploying', 'deleting', 'deploy_failed',
                                                                  'pending', 'warning', 'critical', 'unsupported'),
                                                       nullable=True))
    op.add_column('ibm_instances', sa.Column('ibm_status',
                                             mysql.ENUM('deleting', 'failed', 'paused', 'pausing', 'pending',
                                                        'restarting', 'resuming', 'running', 'starting', 'stopped',
                                                        'stopping'), nullable=False))
    op.add_column('ibm_instance_groups',
                  sa.Column('ibm_status', mysql.ENUM('deleting', 'healthy', 'scaling', 'unhealthy'), nullable=False))
    op.add_column('ibm_instance_group_memberships',
                  sa.Column('ibm_status', mysql.ENUM('deleting', 'failed', 'healthy', 'pending', 'unhealthy'),
                            nullable=False))
    op.add_column('ibm_instance_group_manager_actions',
                  sa.Column('ibm_status', mysql.ENUM('active', 'completed', 'failed', 'incompatible', 'omitted'),
                            nullable=False))
    op.add_column('ibm_images', sa.Column('ibm_status',
                                          mysql.ENUM('available', 'deleting', 'deprecated', 'failed', 'unusable',
                                                     'pending', 'tentative'), nullable=False))
    op.add_column('ibm_floating_ips',
                  sa.Column('ibm_status', mysql.ENUM('available', 'deleting', 'failed', 'pending'), nullable=False))
    op.alter_column('ibm_floating_ips', 'status',
                    existing_type=mysql.ENUM('available', 'deleting', 'failed', 'pending'),
                    type_=mysql.VARCHAR(length=50)
                    )
    op.add_column('ibm_endpoint_gateways', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('ibm_endpoint_gateways', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting',
                                     'suspended')
                    )
    op.alter_column('ibm_endpoint_gateways', 'health_state',
                    type_=mysql.ENUM('ok', 'faulted', 'degraded', 'inapplicable'),
                    existing_type=mysql.VARCHAR(length=50),
                    )
    op.add_column('ibm_dedicated_hosts', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('ibm_dedicated_hosts', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.ENUM('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting',
                                     'suspended'),
                    )
    op.alter_column('ibm_dedicated_hosts', 'state',
                    type_=mysql.ENUM('deleting', 'failed', 'pending', 'available'),
                    existing_type=mysql.VARCHAR(length=50),
                    )
    # ### end Alembic commands ###
