"""empty message

Revision ID: 522ca0951e12
Revises: ce0b5e7cf1eb
Create Date: 2023-03-09 07:30:25.174853

"""

# revision identifiers, used by Alembic.
revision = '522ca0951e12'
down_revision = 'ce0b5e7cf1eb'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('ibm_satellite_clusters', sa.Column('kube_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('ibm_satellite_clusters', 'kube_config')

    # ### end Alembic commands ###
