"""empty message

Revision ID: 542ce660fe38
Revises: cfef370e6122
Create Date: 2022-02-18 14:34:27.313237

"""

# revision identifiers, used by Alembic.
revision = '542ce660fe38'
down_revision = 'cfef370e6122'

import sqlalchemy as sa
from alembic import op

new_type = sa.Enum('ON_HOLD', 'READY', 'PENDING', 'INITIATED', 'RUNNING',
                   'ON_HOLD_WITH_SUCCESS',
                   'ON_HOLD_WITH_FAILURE', 'COMPLETED_SUCCESSFULLY',
                   'COMPLETED_WITH_FAILURE')
old_type = sa.Enum('ON_HOLD', 'PENDING', 'INITIATED', 'RUNNING',
                   'ON_HOLD_WITH_SUCCESS',
                   'ON_HOLD_WITH_FAILURE', 'COMPLETED_SUCCESSFULLY',
                   'COMPLETED_WITH_FAILURE')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows_workspaces',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('name', sa.String(length=512), nullable=False),
                    sa.Column('fe_request_data', sa.JSON(), nullable=True),
                    sa.Column(
                        'status',
                        sa.Enum('ON_HOLD', 'PENDING', 'INITIATED', 'RUNNING',
                                'ON_HOLD_WITH_SUCCESS',
                                'ON_HOLD_WITH_FAILURE', 'COMPLETED_SUCCESSFULLY',
                                'COMPLETED_WITH_FAILURE'), nullable=False
                    ),
                    sa.Column(
                        'state',
                        sa.Enum('ON_HOLD', 'PENDING', 'INITIATED', 'RUNNING', 'ON_HOLD_WITH_SUCCESS',
                                'ON_HOLD_WITH_FAILURE', 'COMPLETED_SUCCESSFULLY',
                                'COMPLETED_WITH_FAILURE'), nullable=False
                    ),
                    sa.Column('executor_running', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('started_at', sa.DateTime(), nullable=True),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.String(length=32), nullable=False),
                    sa.Column('project_id', sa.String(length=32), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('workspace_tree_mappings',
                    sa.Column('root_id', sa.String(length=32), nullable=False),
                    sa.Column('next_root_id', sa.String(length=32), nullable=False),
                    sa.ForeignKeyConstraint(['next_root_id'], ['workflow_roots.id'], ),
                    sa.ForeignKeyConstraint(['root_id'], ['workflow_roots.id'], )
                    )
    op.add_column('workflow_roots', sa.Column('in_focus', sa.Boolean(), nullable=False))
    op.add_column('workflow_roots', sa.Column('workflows_workspace_id', sa.String(length=32), nullable=True))
    op.alter_column('workflow_roots', 'status', type_=new_type, existing_type=old_type, nullable=False)
    op.create_foreign_key('fk_workflow_roots_workflows_workspaces_1', 'workflow_roots', 'workflows_workspaces',
                          ['workflows_workspace_id'],
                          ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workflow_roots_workflows_workspaces_1', 'workflow_roots', type_='foreignkey')
    op.alter_column('workflow_roots', 'status', type_=old_type, existing_type=new_type, nullable=False)
    op.drop_column('workflow_roots', 'workflows_workspace_id')
    op.drop_column('workflow_roots', 'in_focus')
    op.drop_table('workspace_tree_mappings')
    op.drop_table('workflows_workspaces')
    # ### end Alembic commands ###
