"""empty message

Revision ID: 57ca7b892613
Revises: f02a70eaf7ba
Create Date: 2021-12-23 17:48:14.307325

"""

# revision identifiers, used by Alembic.

revision = '57ca7b892613'
down_revision = 'f02a70eaf7ba'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from ibm.models import IBMListenerPolicy

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_listener_and_policy_common',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('LISTENER', 'POLICY'), nullable=False),
    sa.Column('http_status_code', sa.Enum('301', '302', '303', '307', '308'), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('uri', sa.String(length=1024), nullable=True),
    sa.Column('listener_id', sa.String(length=32), nullable=True),
    sa.Column('policy_id', sa.String(length=32), nullable=True),
    sa.Column('pool_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['listener_id'], ['ibm_listeners.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['ibm_lb_listener_policies.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['ibm_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('ibm_lb_listener_policies_ibfk_2', 'ibm_lb_listener_policies', type_='foreignkey')
    op.drop_column('ibm_lb_listener_policies', 'target_lb_redirect_http_status_code')
    op.drop_column('ibm_lb_listener_policies', 'target_lb_redirect_url')
    op.alter_column('ibm_lb_listener_policies', 'status', existing_type=sa.String(50),
                    nullable=True, new_column_name="ibm_status")
    op.alter_column('ibm_lb_listener_policies', 'action',
                    existing_type=sa.Enum(IBMListenerPolicy.ACTION_FORWARD, IBMListenerPolicy.ACTION_REDIRECT,
                                          IBMListenerPolicy.ACTION_REJECT),
                    nullable=True, type_=sa.Enum(*IBMListenerPolicy.ALL_ACTIONS_LIST))
    op.drop_column('ibm_lb_listener_policies', 'target_pool_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_lb_listener_policies', sa.Column('target_pool_id', mysql.VARCHAR(length=32), nullable=True))
    op.alter_column('ibm_lb_listener_policies', 'action',
                    existing_type=sa.Enum(*IBMListenerPolicy.ALL_ACTIONS_LIST),
                    nullable=True,
                    type_=sa.Enum(
                        IBMListenerPolicy.ACTION_FORWARD, IBMListenerPolicy.ACTION_REDIRECT,
                        IBMListenerPolicy.ACTION_REJECT)
                    )
    op.alter_column('ibm_lb_listener_policies', 'ibm_status', existing_type=sa.String(50),
                    nullable=True, new_column_name="status")
    op.add_column('ibm_lb_listener_policies', sa.Column('target_lb_redirect_url', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('ibm_lb_listener_policies', sa.Column('target_lb_redirect_http_status_code', mysql.ENUM('301', '302', '303', '307', '308'), nullable=True))
    op.create_foreign_key('ibm_lb_listener_policies_ibfk_2', 'ibm_lb_listener_policies', 'ibm_pools', ['target_pool_id'], ['id'])
    op.drop_table('ibm_listener_and_policy_common')
    # ### end Alembic commands ###