"""empty message

Revision ID: 5c8b7b8756af
Revises: 93d2a693a6ab
Create Date: 2022-04-20 09:25:08.445599

"""

# revision identifiers, used by Alembic.
revision = '5c8b7b8756af'
down_revision = '93d2a693a6ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_volumes', sa.Column('volume_index', sa.Integer(), nullable=False))
    op.add_column('ibm_instances', sa.Column('volume_migration_report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instances', 'volume_migration_report')
    op.drop_column('ibm_volumes', 'volume_index')
    # ### end Alembic commands ###
