"""empty message

Revision ID: 5e2baea7ec70
Revises: 8e0e84d56031
Create Date: 2021-09-23 19:30:02.318328

"""

# revision identifiers, used by Alembic.
revision = '5e2baea7ec70'
down_revision = '8e0e84d56031'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_operating_systems',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('architecture', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('dedicated_host_only', sa.Boolean(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', 'cloud_id', name='uix_ibm_operation_system_name_region_id_cloud_id')
    )
    op.create_table('ibm_volume_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', 'cloud_id', name='uix_ibm_volume_profile_name_region_id_cloud_id')
    )
    op.create_table('ibm_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'public'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('encryption', sa.Enum('none', 'user_managed'), nullable=False),
    sa.Column('ibm_status', sa.Enum('available', 'deleting', 'deprecated', 'failed', 'unusable', 'pending', 'tentative'), nullable=False),
    sa.Column('ibm_status_reasons', sa.JSON(), nullable=False),
    sa.Column('encryption_key_crn', sa.String(length=255), nullable=True),
    sa.Column('minimum_provisioned_size', sa.Integer(), nullable=True),
    sa.Column('file_checksums_sha256', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=False),
    sa.Column('operating_system_id', sa.String(length=32), nullable=True),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['operating_system_id'], ['ibm_operating_systems.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cloud_id', 'region_id', 'visibility', name='uix_ibm_image_name_region_id_visibility_cloud_id')
    )
    op.create_table('ibm_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('deletable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bootable', sa.Boolean(), nullable=False),
    sa.Column('encryption', sa.Enum('provider_managed', 'user_managed'), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting', 'suspended'), nullable=False),
    sa.Column('minimum_capacity', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('snapshot'), nullable=False),
    sa.Column('encryption_key_crn', sa.String(length=255), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=False),
    sa.Column('operating_system_id', sa.String(length=32), nullable=True),
    sa.Column('source_image_id', sa.String(length=32), nullable=True),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['operating_system_id'], ['ibm_operating_systems.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['source_image_id'], ['ibm_images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', 'cloud_id', name='uix_ibm_snapshots_name_region_id_cloud_id')
    )
    op.create_table('ibm_volumes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.Column('busy', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('encryption', sa.Enum('provider_managed', 'user_managed'), nullable=False),
    sa.Column('iops', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ibm_status_reasons', sa.JSON(), nullable=False),
    sa.Column('ibm_status', sa.Enum('available', 'failed', 'pending', 'pending_deletion', 'unusable'), nullable=False),
    sa.Column('encryption_key_crn', sa.String(length=255), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=False),
    sa.Column('volume_profile_id', sa.String(length=32), nullable=False),
    sa.Column('operating_system_id', sa.String(length=32), nullable=True),
    sa.Column('source_image_id', sa.String(length=32), nullable=True),
    sa.Column('source_snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['operating_system_id'], ['ibm_operating_systems.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['source_image_id'], ['ibm_images.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['ibm_snapshots.id'], ),
    sa.ForeignKeyConstraint(['volume_profile_id'], ['ibm_volume_profiles.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['ibm_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', 'cloud_id', name='uix_ibm_volumes_name_region_id_cloud_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_volumes')
    op.drop_table('ibm_snapshots')
    op.drop_table('ibm_images')
    op.drop_table('ibm_volume_profiles')
    op.drop_table('ibm_operating_systems')
    # ### end Alembic commands ###