"""empty message

Revision ID: 5f1902f75868
Revises: e938594e9639
Create Date: 2022-12-22 11:34:06.673344

"""

# revision identifiers, used by Alembic.
revision = '5f1902f75868'
down_revision = 'e938594e9639'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_cost_per_tags',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ibm_tags', sa.Column('resource_crn', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_tags', 'resource_crn')
    op.drop_table('ibm_cost_per_tags')
    # ### end Alembic commands ###