"""empty message

Revision ID: 602dd9947f03
Revises: f658b81e0004
Create Date: 2021-09-23 23:51:35.331415

"""

# revision identifiers, used by Alembic.
revision = '602dd9947f03'
down_revision = 'f658b81e0004'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('softlayer_clouds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('softlayer_clouds')
    # ### end Alembic commands ###