"""empty message

Revision ID: 609df09ab230
Revises: bf223eb1f30b
Create Date: 2022-08-09 12:08:16.446777

"""

# revision identifiers, used by Alembic.
revision = '609df09ab230'
down_revision = 'bf223eb1f30b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_ibm_name_vpc_id_cloud_id_region_id', table_name='ibm_instances')
    op.create_unique_constraint('uix_ibm_resource_id_cloud_id_region_id', 'ibm_instances', ['resource_id', 'cloud_id', 'region_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ibm_resource_id_cloud_id_region_id', 'ibm_instances', type_='unique')
    op.create_index('uix_ibm_name_vpc_id_cloud_id_region_id', 'ibm_instances', ['name', 'vpc_id', 'cloud_id', 'region_id'], unique=False)
    # ### end Alembic commands ###