"""empty message

Revision ID: 6207c39472fe
Revises: 6de20fb2a47a
Create Date: 2022-10-13 06:13:19.161265

"""

# revision identifiers, used by Alembic.
revision = '6207c39472fe'
down_revision = '6de20fb2a47a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_cloud_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('cost_optimization_update_time', sa.DateTime(), nullable=False),
    sa.Column('cost_optimization_enabled', sa.Boolean(), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_cloud_settings')
    # ### end Alembic commands ###