"""empty message

Revision ID: 653b0482ac1b
Revises: 40afd45bacfa
Create Date: 2022-10-02 09:33:35.279029

"""

# revision identifiers, used by Alembic.
revision = '653b0482ac1b'
down_revision = '40afd45bacfa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instances', 'usage',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instances', 'usage',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###