"""empty message

Revision ID: 69127e238371
Revises: d9d352185045
Create Date: 2021-11-11 02:12:22.268719

"""

# revision identifiers, used by Alembic.
revision = '69127e238371'
down_revision = 'd9d352185045'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ibm_credentials_ibfk_1', 'ibm_credentials', type_='foreignkey')
    op.create_foreign_key('ibm_credentials_ibfk_1', 'ibm_credentials', 'ibm_clouds', ['cloud_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ibm_credentials_ibfk_1', 'ibm_credentials', type_='foreignkey')
    op.create_foreign_key('ibm_credentials_ibfk_1', 'ibm_credentials', 'ibm_clouds', ['cloud_id'], ['id'])
    # ### end Alembic commands ###
