"""empty message

Revision ID: 6b01c7d5f605
Revises: dfbbf7c16247
Create Date: 2022-09-18 18:34:54.829283

"""

# revision identifiers, used by Alembic.
revision = '6b01c7d5f605'
down_revision = 'dfbbf7c16247'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disaster_recovery_backups', sa.Column('started_at', sa.DateTime(), nullable=False))
    op.add_column('disaster_recovery_backups', sa.Column('completed_at', sa.DateTime(), nullable=False))
    op.add_column('disaster_recovery_backups', sa.Column('scheduled', sa.Boolean(), nullable=False))
    op.drop_column('disaster_recovery_backups', 'created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('disaster_recovery_backups', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.drop_column('disaster_recovery_backups', 'scheduled')
    op.drop_column('disaster_recovery_backups', 'completed_at')
    op.drop_column('disaster_recovery_backups', 'started_at')
    # ### end Alembic commands ###