"""empty message

Revision ID: 6de20fb2a47a
Revises: 653b0482ac1b
Create Date: 2022-10-12 06:48:52.427186

"""

# revision identifiers, used by Alembic.
revision = '6de20fb2a47a'
down_revision = '653b0482ac1b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ttl_intervals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
     ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ttl_intervals')
    # ### end Alembic commands ###