"""empty message

Revision ID: 759a50e14fbb
Revises: 7451d973f57f
Create Date: 2022-06-28 06:13:09.590965

"""

# revision identifiers, used by Alembic.
revision = '759a50e14fbb'
down_revision = '7451d973f57f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_endpoint_gateways', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_endpoint_gateways', 'status')
    # ### end Alembic commands ###