"""empty message

Revision ID: 7e0d5c2b2863
Revises: 17cf147063f8
Create Date: 2022-05-11 05:19:14.490017

"""

# revision identifiers, used by Alembic.
revision = '7e0d5c2b2863'
down_revision = '17cf147063f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cm_models',
    sa.Column('softlayer_vsi_id', sa.Integer(), nullable=False),
    sa.Column('cm_meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('softlayer_vsi_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cm_models')
    # ### end Alembic commands ###