"""empty message

Revision ID: 8181c8a821df
Revises: e081ed810d3a
Create Date: 2023-03-22 06:26:53.251225

"""

# revision identifiers, used by Alembic.
revision = '8181c8a821df'
down_revision = 'e081ed810d3a'

from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_dedicated_hosts', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_dedicated_hosts', 'state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_endpoint_gateways', 'health_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_endpoint_gateways', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_kubernetes_clusters', 'status',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('ibm_lb_listener_policies', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_lb_listener_policy_rules', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_listeners', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_load_balancers', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_pool_members', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_pools', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_routing_table_routes', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_routing_tables', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('ibm_snapshots', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_snapshots', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_routing_tables', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_routing_table_routes', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_pools', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_pool_members', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_load_balancers', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_listeners', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_lb_listener_policy_rules', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_lb_listener_policies', 'provisioning_status',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_kubernetes_clusters', 'status',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('ibm_endpoint_gateways', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_endpoint_gateways', 'health_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_dedicated_hosts', 'state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('ibm_dedicated_hosts', 'lifecycle_state',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    # ### end Alembic commands ###
