"""empty message

Revision ID: 82b6cb22b479
Revises: 5c134f42131d
Create Date: 2023-02-26 06:17:45.626432

"""

# revision identifiers, used by Alembic.
revision = '82b6cb22b479'
down_revision = '5c134f42131d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_discovery_controller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.Enum('ResourceController'), nullable=False),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO ibm_discovery_controller (service_name, flag, description) "
               "VALUES ('ResourceController', True, 'Fetch complete data if flag is True')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_discovery_controller')
    # ### end Alembic commands ###