"""empty message

Revision ID: 85278b9fadd7
Revises: fc24da342add
Create Date: 2022-01-17 08:52:02.201342

"""

# revision identifiers, used by Alembic.
revision = '85278b9fadd7'
down_revision = 'fc24da342add'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_cloud_object_storages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('guid', sa.String(length=255), nullable=False),
    sa.Column('crn', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('migrated', sa.Boolean(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_cos_buckets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('location_constraint', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('standard', 'smart'), nullable=False),
    sa.Column('cloud_object_storage_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['cloud_object_storage_id'], ['ibm_cloud_object_storages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_bucket_regions',
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('bucket_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['ibm_cos_buckets.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.PrimaryKeyConstraint('region_id', 'bucket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_bucket_regions')
    op.drop_table('ibm_cos_buckets')
    op.drop_table('ibm_cloud_object_storages')
    # ### end Alembic commands ###