"""empty message

Revision ID: 8821381f0d42
Revises: 602dd9947f03
Create Date: 2021-10-10 16:30:18.026527

"""

# revision identifiers, used by Alembic.
revision = '8821381f0d42'
down_revision = '602dd9947f03'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_clouds', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.alter_column('ibm_clouds', 'api_key_id', existing_type=mysql.VARCHAR(length=500), nullable=True)
    op.alter_column(
        'ibm_clouds', 'status',
        type_=mysql.ENUM('AUTHENTICATING', 'VALID', 'INVALID', 'ERROR_DUPLICATE_RESOURCE_GROUPS', 'DELETING'),
        existing_type=mysql.ENUM('AUTHENTICATING', 'VALID', 'INVALID', 'ERROR_DUPLICATE_RESOURCE_GROUPS'),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ibm_clouds', 'status',
        type_=mysql.ENUM('AUTHENTICATING', 'VALID', 'INVALID', 'ERROR_DUPLICATE_RESOURCE_GROUPS'),
        existing_type=mysql.ENUM('AUTHENTICATING', 'VALID', 'INVALID', 'ERROR_DUPLICATE_RESOURCE_GROUPS', 'DELETING'),
        nullable=False
    )
    op.alter_column('ibm_clouds', 'api_key_id', existing_type=mysql.VARCHAR(length=500), nullable=False)
    op.drop_column('ibm_clouds', 'deleted')
    # ### end Alembic commands ###
