"""empty message

Revision ID: 8c224e92c927
Revises: 08f65f6ff945
Create Date: 2022-02-07 12:57:08.578653

"""

# revision identifiers, used by Alembic.
revision = '8c224e92c927'
down_revision = '08f65f6ff945'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_listeners', sa.Column('pool_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('fk_ibm_listeners_ibm_pools', 'ibm_listeners', 'ibm_pools', ['pool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ibm_listeners_ibm_pools', 'ibm_listeners', type_='foreignkey')
    op.drop_column('ibm_listeners', 'pool_id')
    # ### end Alembic commands ###
