"""empty message

Revision ID: 8c6ee7e0c970
Revises: 07b4f816a4bd
Create Date: 2022-02-01 07:43:28.804649

"""

# revision identifiers, used by Alembic.
revision = '8c6ee7e0c970'
down_revision = '07b4f816a4bd'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_pools', sa.Column('region_id', sa.String(length=32), nullable=False))
    op.add_column('ibm_pools', sa.Column('cloud_id', sa.String(length=32), nullable=False))
    op.create_foreign_key('fk_ibm_pools_ibm_clouds_id_cloud_id', 'ibm_pools', 'ibm_clouds', ['cloud_id'], ['id'])
    op.create_foreign_key('fk_ibm_pools_ibm_regions_id_region_id', 'ibm_pools', 'ibm_regions', ['region_id'], ['id'])
    op.drop_constraint('ibm_listeners_ibfk_3', 'ibm_listeners', type_='foreignkey')
    op.drop_column('ibm_listeners', 'pool_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_listeners', sa.Column('pool_id', mysql.VARCHAR(length=32), nullable=True))
    op.create_foreign_key('ibm_listeners_ibfk_3', 'ibm_listeners', 'ibm_pools', ['pool_id'], ['id'])
    op.drop_constraint('fk_ibm_pools_ibm_regions_id_region_id', 'ibm_pools', type_='foreignkey')
    op.drop_constraint('fk_ibm_pools_ibm_clouds_id_cloud_id', 'ibm_pools', type_='foreignkey')
    op.drop_column('ibm_pools', 'cloud_id')
    op.drop_column('ibm_pools', 'region_id')
    # ### end Alembic commands ###
