"""empty message

Revision ID: 91051cdbe04c
Revises: 4f05868f3f07
Create Date: 2021-12-30 12:22:36.682357

"""

# revision identifiers, used by Alembic.
revision = '91051cdbe04c'
down_revision = '4f05868f3f07'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_tasks', sa.Column('result', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_tasks', 'result')
    # ### end Alembic commands ###
