"""empty message

Revision ID: 913f032553a1
Revises: 5f1902f75868
Create Date: 2022-12-18 21:32:28.437074

"""

# revision identifiers, used by Alembic.
revision = '913f032553a1'
down_revision = '5f1902f75868'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_resource_controller_data',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('last_operation', sa.JSON(), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_resource_controller_data')
    # ### end Alembic commands ###
