"""empty message

Revision ID: 9704abaa163d
Revises: 9f26086c64b0
Create Date: 2022-10-21 21:23:35.568205

"""

# revision identifiers, used by Alembic.
revision = '9704abaa163d'
down_revision = '9f26086c64b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_recovery_scheduled_policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('backup_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_cron_pattern', sa.String(length=150), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('disaster_recovery_resource_blueprints', sa.Column('scheduled_policy_state', sa.Enum('ACTIVE', 'INACTIVE'), nullable=False))
    op.add_column('disaster_recovery_resource_blueprints', sa.Column('last_backup_taken_at', sa.DateTime(), nullable=True))
    op.add_column('disaster_recovery_resource_blueprints', sa.Column('next_backup_scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('disaster_recovery_resource_blueprints', sa.Column('user_id', sa.String(length=32), nullable=False))
    op.add_column('disaster_recovery_resource_blueprints', sa.Column('draas_scheduled_policy_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('draas_bp_draas_schedule_policy', 'disaster_recovery_resource_blueprints', 'disaster_recovery_scheduled_policies', ['draas_scheduled_policy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('draas_bp_draas_schedule_policy', 'disaster_recovery_resource_blueprints', type_='foreignkey')
    op.drop_column('disaster_recovery_resource_blueprints', 'draas_scheduled_policy_id')
    op.drop_column('disaster_recovery_resource_blueprints', 'user_id')
    op.drop_column('disaster_recovery_resource_blueprints', 'next_backup_scheduled_at')
    op.drop_column('disaster_recovery_resource_blueprints', 'last_backup_taken_at')
    op.drop_column('disaster_recovery_resource_blueprints', 'scheduled_policy_state')
    op.drop_table('disaster_recovery_scheduled_policies')
    # ### end Alembic commands ###