"""empty message

Revision ID: 9737b29697ac
Revises: 91051cdbe04c
Create Date: 2022-01-11 22:21:25.120536

"""

# revision identifiers, used by Alembic.
revision = '9737b29697ac'
down_revision = '91051cdbe04c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_images', 'ibm_encryption')
    op.drop_column('ibm_images', 'ibm_visible')
    op.alter_column('ibm_lb_listener_policies', 'action',
               existing_type=mysql.ENUM('forward', 'redirect', 'reject', 'https_redirect'),
               nullable=False)
    op.alter_column('ibm_lb_listener_policies', 'ibm_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ibm_load_balancers', 'host_name',
               new_column_name='hostname',
               existing_type=sa.String(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_load_balancers', 'hostname',
               new_column_name='host_name',
               existing_type=sa.String(length=64),
               nullable=False)
    op.alter_column('ibm_lb_listener_policies', 'ibm_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ibm_lb_listener_policies', 'action',
               existing_type=mysql.ENUM('forward', 'redirect', 'reject', 'https_redirect'),
               nullable=True)
    op.add_column('ibm_images', sa.Column('ibm_visible', mysql.ENUM('public', 'private'), nullable=False))
    op.add_column('ibm_images', sa.Column('ibm_encryption', mysql.ENUM('none', 'user_managed'), nullable=False))
    # ### end Alembic commands ###
