"""empty message

Revision ID: 97a3c41e3803
Revises: 913f032553a1
Create Date: 2023-01-25 11:40:10.406670

"""

# revision identifiers, used by Alembic.
revision = '97a3c41e3803'
down_revision = '913f032553a1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_ibm_resource_id_cloud_id', table_name='ibm_kubernetes_clusters')
    op.create_unique_constraint('uix_ibm_resource_id_cloud_id_vpc_id', 'ibm_kubernetes_clusters', ['resource_id', 'cloud_id', 'vpc_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ibm_resource_id_cloud_id_vpc_id', 'ibm_kubernetes_clusters', type_='unique')
    op.create_index('uix_ibm_resource_id_cloud_id', 'ibm_kubernetes_clusters', ['resource_id', 'cloud_id'], unique=False)
    # ### end Alembic commands ###
