"""empty message

Revision ID: 99f760976efd
Revises: da59f731e0d8
Create Date: 2022-11-17 10:40:27.699745

"""

# revision identifiers, used by Alembic.
revision = '99f760976efd'
down_revision = 'da59f731e0d8'

from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows_workspaces', 'source_cloud',
                    existing_type=mysql.ENUM('AWS', 'IBM', 'SOFTLAYER', 'GCP', 'AZURE', 'ON_PREM'),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows_workspaces', 'source_cloud',
                    existing_type=mysql.ENUM('AWS', 'IBM', 'SOFTLAYER', 'GCP', 'AZURE', 'ON_PREM'),
                    nullable=False)
    # ### end Alembic commands ###
