"""empty message

Revision ID: 9d4eae8e2a7b
Revises: cb9176357ebd
Create Date: 2022-01-25 17:43:57.821669

"""

# revision identifiers, used by Alembic.
revision = '9d4eae8e2a7b'
down_revision = 'cb9176357ebd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_cos_buckets', sa.Column('resiliency', sa.Enum('cross-region', 'regional', 'single-site'), nullable=False))
    op.drop_column('ibm_cos_buckets', 'region_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_cos_buckets', sa.Column('region_id', mysql.VARCHAR(length=32), nullable=False))
    op.drop_column('ibm_cos_buckets', 'resiliency')
    # ### end Alembic commands ###