"""empty message

Revision ID: 9f26086c64b0
Revises: b333bc588d7e
Create Date: 2022-10-19 14:53:40.186055

"""

# revision identifiers, used by Alembic.
revision = '9f26086c64b0'
down_revision = 'b333bc588d7e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_ike_policy', 'dh_group',
                    existing_type=sa.Enum("14", "19", "2", "5"),
                    type_=mysql.ENUM("14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "24", "31", "5"),
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_ike_policy', 'dh_group',
                    existing_type=mysql.ENUM("14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "24", "31", "5"),
                    type_=sa.Enum("14", "19", "2", "5"),
                    )
    # ### end Alembic commands ###
