"""empty message

Revision ID: abd569b59517
Revises: 316358bf8fb0
Create Date: 2022-11-01 10:17:25.726487

"""

# revision identifiers, used by Alembic.
revision = 'abd569b59517'
down_revision = '316358bf8fb0'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows_workspaces',
                  sa.Column('source_cloud', sa.Enum('AWS', 'IBM', 'SOFTLAYER', 'GCP', 'AZURE', 'ON_PREM'),
                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows_workspaces', 'source_cloud')
    # ### end Alembic commands ###
