"""empty message

Revision ID: b333bc588d7e
Revises: 44e65514659e
Create Date: 2022-10-19 08:06:09.273117

"""

# revision identifiers, used by Alembic.
revision = 'b333bc588d7e'
down_revision = '44e65514659e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_resource_costs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=512), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.rename_table('ibm_individual_resource_costs', 'ibm_services_costs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('ibm_services_costs', 'ibm_individual_resource_costs')
    op.drop_table('ibm_resource_costs')
    # ### end Alembic commands ###