"""empty message

Revision ID: baad9d1bd711
Revises: 5e2baea7ec70
Create Date: 2021-09-23 19:36:02.038187

"""

# revision identifiers, used by Alembic.
revision = 'baad9d1bd711'
down_revision = '5e2baea7ec70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_images', sa.Column('source_volume_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('ibm_images_ibfk_5', 'ibm_images', 'ibm_volumes', ['source_volume_id'], ['id'])
    op.add_column('ibm_snapshots', sa.Column('source_volume_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('ibm_snapshots_ibfk_6', 'ibm_snapshots', 'ibm_volumes', ['source_volume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ibm_snapshots_ibfk_6', 'ibm_snapshots', type_='foreignkey')
    op.drop_column('ibm_snapshots', 'source_volume_id')
    op.drop_constraint('ibm_images_ibfk_5', 'ibm_images', type_='foreignkey')
    op.drop_column('ibm_images', 'source_volume_id')
    # ### end Alembic commands ###
