"""empty message

Revision ID: bf223eb1f30b
Revises: 2c6d529a8ee7
Create Date: 2022-08-08 21:35:22.585732

"""

# revision identifiers, used by Alembic.
revision = 'bf223eb1f30b'
down_revision = '2c6d529a8ee7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_ibm_ssh_name_region_id_cloud_id', table_name='ibm_ssh_keys')
    op.create_unique_constraint('uix_ibm_ssh_resource_id_cloud_id', 'ibm_ssh_keys', ['resource_id', 'cloud_id'])
    op.drop_index('uix_ibm_volumes_name_region_id_cloud_id', table_name='ibm_volumes')
    op.create_unique_constraint('uix_ibm_volumes_resource_id_cloud_id', 'ibm_volumes', ['resource_id', 'cloud_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ibm_volumes_resource_id_cloud_id', 'ibm_volumes', type_='unique')
    op.create_index('uix_ibm_volumes_name_region_id_cloud_id', 'ibm_volumes', ['name', 'region_id', 'cloud_id'], unique=False)
    op.drop_constraint('uix_ibm_ssh_resource_id_cloud_id', 'ibm_ssh_keys', type_='unique')
    op.create_index('uix_ibm_ssh_name_region_id_cloud_id', 'ibm_ssh_keys', ['name', 'region_id', 'cloud_id'], unique=False)
    # ### end Alembic commands ###