"""empty message

Revision ID: c042664dd260
Revises: b8d6daed3c33
Create Date: 2022-08-24 18:04:20.830926

"""

# revision identifiers, used by Alembic.
revision = 'c042664dd260'
down_revision = 'b8d6daed3c33'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_transit_gateways',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('global', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_transit_gateways')
    # ### end Alembic commands ###