"""empty message

Revision ID: c3ee5869d109
Revises: 4869be72602a
Create Date: 2021-09-23 22:42:14.750551

"""

# revision identifiers, used by Alembic.
revision = 'c3ee5869d109'
down_revision = '4869be72602a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_load_balancer_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=False),
    sa.Column('logging_supported_type', sa.Enum('fixed'), nullable=False),
    sa.Column('logging_supported_value', sa.JSON(), nullable=False),
    sa.Column('security_groups_supported_type', sa.Enum('fixed', 'dependent'), nullable=False),
    sa.Column('security_groups_supported_value', sa.Boolean(), nullable=True),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_load_balancers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('host_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('private_ips', sa.JSON(), nullable=False),
    sa.Column('public_ips', sa.JSON(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('crn', sa.String(length=500), nullable=False),
    sa.Column('logging_datapath_active', sa.Boolean(), nullable=False),
    sa.Column('operating_status', sa.Enum('offline', 'online'), nullable=False),
    sa.Column('security_groups_supported', sa.Boolean(), nullable=False),
    sa.Column('provisioning_status', sa.Enum('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending', 'update_pending'), nullable=False),
    sa.Column('load_balancer_profile_id', sa.String(length=32), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['load_balancer_profile_id'], ['ibm_load_balancer_profiles.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'vpc_id', 'cloud_id', 'region_id', name='uix_ibm_lb_name_vpc_cloud_id_region_id')
    )
    op.create_table('ibm_load_balancer_statistics',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('active_connections', sa.BigInteger(), nullable=False),
    sa.Column('connection_rate', sa.Float(), nullable=False),
    sa.Column('data_processed_this_month', sa.BigInteger(), nullable=False),
    sa.Column('throughput', sa.Float(), nullable=False),
    sa.Column('load_balancer_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['load_balancer_id'], ['ibm_load_balancers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_load_balancers_security_groups',
    sa.Column('load_balancer_id', sa.String(length=32), nullable=False),
    sa.Column('security_group_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['load_balancer_id'], ['ibm_load_balancers.id'], ),
    sa.ForeignKeyConstraint(['security_group_id'], ['ibm_security_groups.id'], ),
    sa.PrimaryKeyConstraint('load_balancer_id', 'security_group_id')
    )
    op.create_table('ibm_pools',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.Enum('least_connections', 'round_robin', 'weighted_round_robin'), nullable=False),
    sa.Column('protocol', sa.Enum('https', 'http', 'tcp'), nullable=False),
    sa.Column('provisioning_status', sa.Enum('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending', 'update_pending'), nullable=False),
    sa.Column('proxy_protocol', sa.Enum('v1', 'v2', 'disabled'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('load_balancer_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['load_balancer_id'], ['ibm_load_balancers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'load_balancer_id', name='uix_ibm_pool_name_load_balancer_id')
    )
    op.create_table('ibm_lb_pool_session_persistence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('source_ip', 'app_cookie', 'http_cookie'), nullable=False),
    sa.Column('cookie_name', sa.String(length=255), nullable=True),
    sa.Column('lb_pool_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['lb_pool_id'], ['ibm_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_listeners',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('accept_proxy_protocol', sa.Boolean(), nullable=False),
    sa.Column('protocol', sa.Enum('https', 'http', 'tcp'), nullable=False),
    sa.Column('provisioning_status', sa.Enum('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending', 'update_pending'), nullable=False),
    sa.Column('certificate_instance_crn', sa.String(length=300), nullable=True),
    sa.Column('connection_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('load_balancer_id', sa.String(length=32), nullable=False),
    sa.Column('pool_id', sa.String(length=32), nullable=True),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['load_balancer_id'], ['ibm_load_balancers.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['ibm_pools.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_load_balancer_subnets',
    sa.Column('load_balancer_id', sa.String(length=32), nullable=False),
    sa.Column('subnets_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['load_balancer_id'], ['ibm_load_balancers.id'], ),
    sa.ForeignKeyConstraint(['subnets_id'], ['ibm_subnets.id'], ),
    sa.PrimaryKeyConstraint('load_balancer_id', 'subnets_id')
    )
    op.create_table('ibm_pool_health_monitors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('https', 'http', 'tcp'), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('url_path', sa.String(length=2048), nullable=True),
    sa.Column('lb_pool_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['lb_pool_id'], ['ibm_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_lb_listener_policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('forward', 'redirect', 'reject'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provisioning_status', sa.Enum('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending', 'update_pending'), nullable=False),
    sa.Column('target_lb_redirect_http_status_code', sa.Enum('301', '302', '303', '307', '308'), nullable=True),
    sa.Column('target_lb_redirect_url', sa.String(length=1024), nullable=True),
    sa.Column('lb_listener_id', sa.String(length=32), nullable=False),
    sa.Column('target_pool_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['lb_listener_id'], ['ibm_listeners.id'], ),
    sa.ForeignKeyConstraint(['target_pool_id'], ['ibm_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_pool_members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('provisioning_status', sa.Enum('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending', 'update_pending'), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('health', sa.Enum('ok', 'faulted', 'unknown'), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('target_ip_address', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pool_id', sa.String(length=32), nullable=False),
    sa.Column('target_instance_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['ibm_pools.id'], ),
    sa.ForeignKeyConstraint(['target_instance_id'], ['ibm_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_lb_listener_policy_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('provisioning_status', sa.Enum('active', 'create_pending', 'delete_pending', 'failed', 'maintenance_pending', 'update_pending'), nullable=False),
    sa.Column('condition', sa.Enum('contains', 'equals', 'matches_regex'), nullable=False),
    sa.Column('value', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('header', 'hostname', 'path', 'query', 'body'), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('lb_listener_policy_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['lb_listener_policy_id'], ['ibm_lb_listener_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_lb_listener_policy_rules')
    op.drop_table('ibm_pool_members')
    op.drop_table('ibm_lb_listener_policies')
    op.drop_table('ibm_pool_health_monitors')
    op.drop_table('ibm_load_balancer_subnets')
    op.drop_table('ibm_listeners')
    op.drop_table('ibm_lb_pool_session_persistence')
    op.drop_table('ibm_pools')
    op.drop_table('ibm_load_balancers_security_groups')
    op.drop_table('ibm_load_balancer_statistics')
    op.drop_table('ibm_load_balancers')
    op.drop_table('ibm_load_balancer_profiles')
    # ### end Alembic commands ###