"""empty message
Revision ID: cb9176357ebd
Revises: 18590eb1bd27
Create Date: 2022-01-18 18:52:23.347894
"""

# revision identifiers, used by Alembic.
revision = 'cb9176357ebd'
down_revision = '18590eb1bd27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_security_group_rules', 'tcp_udp_port_min', new_column_name='port_min', existing_type=sa.Integer(), nullable=True)
    op.alter_column('ibm_security_group_rules', 'tcp_udp_port_max', new_column_name='port_max', existing_type=sa.Integer(), nullable=True)
    op.alter_column('ibm_security_group_rules', 'icmp_type', new_column_name='type', existing_type=sa.Integer(), nullable=True)
    op.alter_column('ibm_security_group_rules', 'icmp_code', new_column_name='code', existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_security_group_rules', 'port_min', new_column_name='tcp_udp_port_min', existing_type=sa.Integer(), nullable=True)
    op.alter_column('ibm_security_group_rules', 'port_max', new_column_name='tcp_udp_port_max', existing_type=sa.Integer(), nullable=True)
    op.alter_column('ibm_security_group_rules', 'type', new_column_name='icmp_type', existing_type=sa.Integer(), nullable=True)
    op.alter_column('ibm_security_group_rules', 'code', new_column_name='icmp_code', existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###