"""empty message

Revision ID: ccc2eafeb22b
Revises: cde3cfeb4e82
Create Date: 2022-12-10 13:00:30.081952

"""

# revision identifiers, used by Alembic.
revision = 'ccc2eafeb22b'
down_revision = 'cde3cfeb4e82'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_resource_instances_cost',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=512), nullable=False),
    sa.Column('crn', sa.String(length=512), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('cost_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['cost_id'], ['ibm_costs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_resource_instances_daily_cost',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=512), nullable=False),
    sa.Column('crn', sa.String(length=512), nullable=False),
    sa.Column('daily_cost', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cost_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['cost_id'], ['ibm_costs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ibm_resource_instances_daily_cost_date'), 'ibm_resource_instances_daily_cost', ['date'], unique=False)
    op.create_table('ibm_resources_cost',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('billable_cost', sa.Float(), nullable=False),
    sa.Column('non_billable_cost', sa.Float(), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('cost_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['cost_id'], ['ibm_costs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ibm_resource_costs')
    op.drop_table('ibm_services_costs')
    op.drop_index('ix_ibm_cost_tracking_date', table_name='ibm_cost_tracking')
    op.drop_table('ibm_cost_tracking')
    op.add_column('ibm_idle_resources', sa.Column('estimated_savings', sa.Float(), nullable=True))
    op.add_column('ibm_idle_resources', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('ibm_right_sizing_recommendations', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_idle_resources', 'estimated_savings')
    op.drop_column('ibm_right_sizing_recommendations', 'created_at')
    op.drop_column('ibm_idle_resources', 'created_at')
    op.create_table('ibm_cost_tracking',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('cost', mysql.FLOAT(), nullable=False),
    sa.Column('estimated_savings', mysql.FLOAT(), nullable=False),
    sa.Column('optimized_cost', mysql.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('cloud_id', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], name='ibm_cost_tracking_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ibm_cost_tracking_date', 'ibm_cost_tracking', ['date'], unique=False)
    op.create_table('ibm_services_costs',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('resource_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('billable_cost', mysql.FLOAT(), nullable=False),
    sa.Column('non_billable_cost', mysql.FLOAT(), nullable=False),
    sa.Column('resource_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cost_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('cloud_id', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], name='fk_idc_clouds'),
    sa.ForeignKeyConstraint(['cost_id'], ['ibm_costs.id'], name='ibm_services_costs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ibm_resource_costs',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('resource_id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('cost', mysql.FLOAT(), nullable=False),
    sa.Column('estimated_cost', mysql.FLOAT(), nullable=False),
    sa.Column('cloud_id', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], name='ibm_resource_costs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('ibm_resources_cost')
    op.drop_index(op.f('ix_ibm_resource_instances_daily_cost_date'), table_name='ibm_resource_instances_daily_cost')
    op.drop_table('ibm_resource_instances_daily_cost')
    op.drop_table('ibm_resource_instances_cost')
    # ### end Alembic commands ###