"""empty message

Revision ID: cde3cfeb4e82
Revises: 99f760976efd
Create Date: 2022-11-29 07:55:14.645563

"""

# revision identifiers, used by Alembic.
revision = 'cde3cfeb4e82'
down_revision = '99f760976efd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_cos_buckets', 'type',
               existing_type=mysql.ENUM('standard', 'smart', 'flex', 'cold', 'vault', 'onerate_active'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_cos_buckets', 'type',
               existing_type=mysql.ENUM('standard', 'smart', 'flex', 'cold', 'vault'),
               nullable=True)
    # ### end Alembic commands ###