"""empty message

Revision ID: ce0b5e7cf1eb
Revises: 522aae419cfe
Create Date: 2023-03-03 06:08:41.732697

"""

# revision identifiers, used by Alembic.
revision = 'ce0b5e7cf1eb'
down_revision = '522aae419cfe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_satellite_locations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.Column('zones', sa.String(length=255), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_satellite_clusters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('pod_subnet', sa.String(length=255), nullable=True),
    sa.Column('service_subnet', sa.String(length=255), nullable=True),
    sa.Column('master_kube_version', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('cluster_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('workloads', sa.JSON(), nullable=True),
    sa.Column('ingress', sa.JSON(), nullable=True),
    sa.Column('service_endpoint', sa.JSON(), nullable=True),
    sa.Column('infrastructure_topology', sa.String(255), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('sat_location', sa.String(length=32), nullable=True),
    sa.Column('region_id', sa.String(length=32), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sat_location'], ['ibm_satellite_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'cloud_id', name='uix_ibm_resource_id_cloud_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_satellite_clusters')
    op.drop_table('ibm_satellite_locations')
    # ### end Alembic commands ###
