"""empty message

Revision ID: cf82455d500c
Revises: 3535a742abd6
Create Date: 2022-03-07 06:47:17.713153

"""

# revision identifiers, used by Alembic.
revision = 'cf82455d500c'
down_revision = '3535a742abd6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instance_group_manager_actions', 'min_membership_count')
    op.drop_column('ibm_instance_group_manager_actions', 'max_membership_count')
    op.add_column('ibm_instance_group_managers', sa.Column('cloud_id', sa.String(length=32), nullable=False))
    op.create_foreign_key("fk_ibm_instance_group_managers_ibm_clouds", 'ibm_instance_group_managers', 'ibm_clouds', ['cloud_id'], ['id'])
    op.add_column('ibm_instance_groups', sa.Column('load_balancer_id', sa.String(length=32), nullable=True))
    op.alter_column('ibm_instance_groups', 'load_balancer_pool_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=True)
    op.create_foreign_key('fk_ibm_instance_groups_ibm_load_balancers_id_load_balancer_id', 'ibm_instance_groups',
                          'ibm_load_balancers', ['load_balancer_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ibm_instance_groups_ibm_load_balancers_id_load_balancer_id', 'ibm_instance_groups',
                       type_='foreignkey')
    op.alter_column('ibm_instance_groups', 'load_balancer_pool_id',
                    existing_type=mysql.VARCHAR(length=32),
                    nullable=False)
    op.drop_column('ibm_instance_groups', 'load_balancer_id')
    op.drop_constraint("fk_ibm_instance_group_managers_ibm_clouds", 'ibm_instance_group_managers', type_='foreignkey')
    op.drop_column('ibm_instance_group_managers', 'cloud_id')
    op.add_column('ibm_instance_group_manager_actions', sa.Column('max_membership_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ibm_instance_group_manager_actions', sa.Column('min_membership_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###