"""empty message
Revision ID: cfef370e6122
Revises: 119601bc7365
Create Date: 2022-03-10 06:26:40.730243
"""

# revision identifiers, used by Alembic.
revision = 'cfef370e6122'
down_revision = '119601bc7365'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_dashboard_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pin_status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_dashboard_settings')
    # ### end Alembic commands ###