"""empty message

Revision ID: d00ab83f8e71
Revises: 3191b5429d81
Create Date: 2021-12-06 04:35:29.919134

"""

# revision identifiers, used by Alembic.
revision = 'd00ab83f8e71'
down_revision = '3191b5429d81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_ibm_floating_ip_name_region_id_cloud_id', table_name='ibm_floating_ips')
    op.create_unique_constraint('uix_ibm_floating_ip_name_zone_id_cloud_id', 'ibm_floating_ips', ['name', 'zone_id', 'cloud_id'])
    op.add_column('ibm_network_interfaces', sa.Column('cloud_id', sa.String(length=32), nullable=False))
    op.create_foreign_key("FK_ibm_network_interfaces_ibm_network_interfaces", 'ibm_network_interfaces', 'ibm_clouds', ['cloud_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("FK_ibm_network_interfaces_ibm_network_interfaces", 'ibm_network_interfaces', type_='foreignkey')
    op.drop_column('ibm_network_interfaces', 'cloud_id')
    op.drop_constraint('uix_ibm_floating_ip_name_zone_id_cloud_id', 'ibm_floating_ips', type_='unique')
    op.create_index('uix_ibm_floating_ip_name_region_id_cloud_id', 'ibm_floating_ips', ['name', 'region_id', 'cloud_id'], unique=False)
    # ### end Alembic commands ###