"""empty message

Revision ID: d57adec6ee15
Revises: daae9bf3c02d
Create Date: 2022-02-25 11:27:10.196685

"""

# revision identifiers, used by Alembic.
revision = 'd57adec6ee15'
down_revision = 'daae9bf3c02d'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_kubernetes_clusters', sa.Column('status', sa.String(length=255), nullable=True))
    op.add_column('ibm_kubernetes_clusters', sa.Column('ibm_state', sa.Enum('normal', 'deploying', 'deleting', 'deploy_failed', 'pending'), nullable=True))
    op.alter_column('ibm_kubernetes_clusters', 'disable_public_service_endpoint',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=True)
    op.drop_column('ibm_kubernetes_clusters', 'state')
    op.drop_column('ibm_kubernetes_clusters', 'ibm_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_kubernetes_clusters', sa.Column('ibm_status', mysql.ENUM('normal', 'deploying', 'deleting', 'failed', 'pending'), nullable=True))
    op.add_column('ibm_kubernetes_clusters', sa.Column('state', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('ibm_kubernetes_clusters', 'disable_public_service_endpoint',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=False)
    op.drop_column('ibm_kubernetes_clusters', 'ibm_state')
    op.drop_column('ibm_kubernetes_clusters', 'status')
    # ### end Alembic commands ###
