"""empty message

Revision ID: d5c3d38be02b
Revises: 6b01c7d5f605
Create Date: 2022-09-19 19:01:11.863409

"""

# revision identifiers, used by Alembic.
revision = 'd5c3d38be02b'
down_revision = '6b01c7d5f605'

from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_kubernetes_clusters', 'ibm_state',
                    existing_type=mysql.ENUM('normal', 'deploying', 'deleting', 'deploy_failed', 'pending', 'warning'),
                    type_=mysql.ENUM('normal', 'deploying', 'deleting', 'deploy_failed', 'pending', 'warning',
                                     'critical', 'unsupported'))  # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ### # ### end Alembic commands ###
    op.alter_column('ibm_kubernetes_clusters', 'ibm_state',
                    existing_type=mysql.ENUM('normal', 'deploying', 'deleting', 'deploy_failed', 'pending', 'warning'),
                    type_=mysql.ENUM('normal', 'deploying', 'deleting', 'deploy_failed', 'pending', 'warning',
                                     'critical'))
