"""empty message

Revision ID: d741aeb2fa9f
Revises: 5511252d2464
Create Date: 2021-11-12 11:51:13.972802

"""

# revision identifiers, used by Alembic.
revision = 'd741aeb2fa9f'
down_revision = '5511252d2464'

from alembic import op
import sqlalchemy as sa

new_type = sa.Enum("tiered", "custom")
old_type = sa.String(length=255)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_volume_profiles', u'family', type_=new_type,
                    existing_type=old_type, nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_volume_profiles', u'family', type_=old_type,
                    existing_type=new_type, nullable=True)
    # ### end Alembic commands ###

