"""empty message

Revision ID: d79fc8b34aa1
Revises: 542ce660fe38
Create Date: 2022-04-20 18:52:15.989261

"""

# revision identifiers, used by Alembic.
revision = 'd79fc8b34aa1'
down_revision = '542ce660fe38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_pool_members', sa.Column('subnet_id', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_pool_members', 'subnet_id')
    # ### end Alembic commands ###