"""empty message

Revision ID: d8fafc7cf1d1
Revises: 7639cdd3320e
Create Date: 2021-09-23 18:02:25.139902

"""

# revision identifiers, used by Alembic.
revision = 'd8fafc7cf1d1'
down_revision = '7639cdd3320e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_vpc_networks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ibm_status', sa.Enum('available', 'failed', 'pending', 'deleting'), nullable=False),
    sa.Column('classic_access', sa.Boolean(), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cloud_id', 'region_id', name='uix_ibm_vpc_network_name_cloud_id_region_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_vpc_networks')
    # ### end Alembic commands ###