"""empty message

Revision ID: d8ffa03d07a7
Revises: 00d2abf81b69
Create Date: 2022-09-28 12:24:37.073410

"""

# revision identifiers, used by Alembic.
revision = 'd8ffa03d07a7'
down_revision = '00d2abf81b69'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_idle_resources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('db_resource_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('marked_at', sa.DateTime(), nullable=False),
    sa.Column('resource_json', sa.JSON(), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=True),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ibm_idle_resources_db_resource_id'), 'ibm_idle_resources', ['db_resource_id'], unique=False)
    op.add_column('ibm_individual_resource_costs', sa.Column('cloud_id', sa.String(length=32), nullable=False))
    op.create_foreign_key('fk_idc_clouds', 'ibm_individual_resource_costs', 'ibm_clouds', ['cloud_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_idc_clouds', 'ibm_individual_resource_costs', type_='foreignkey')
    op.drop_column('ibm_individual_resource_costs', 'cloud_id')
    op.drop_index(op.f('ix_ibm_idle_resources_db_resource_id'), table_name='ibm_idle_resources')
    op.drop_table('ibm_idle_resources')
    # ### end Alembic commands ###