"""empty message

Revision ID: d9d352185045
Revises: 8821381f0d42
Create Date: 2021-10-23 17:48:51.259921

"""

# revision identifiers, used by Alembic.
revision = 'd9d352185045'
down_revision = '8821381f0d42'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_resource_groups', 'href')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_resource_groups', sa.Column('href', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###