"""empty message

Revision ID: da59f731e0d8
Revises: abd569b59517
Create Date: 2022-10-21 10:43:24.088256

"""

# revision identifiers, used by Alembic.
revision = 'da59f731e0d8'
down_revision = 'abd569b59517'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_cost_tracking',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('estimated_savings', sa.Float(), nullable=False),
    sa.Column('optimized_cost', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ibm_cost_tracking_date'), 'ibm_cost_tracking', ['date'], unique=False)

    op.create_table('ibm_resource_tracking',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=256), nullable=False),
    sa.Column('estimated_savings', sa.Float(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_taken_at', sa.DateTime(), nullable=False),
    sa.Column('resource_json', sa.JSON(), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_resource_tracking')
    op.drop_index(op.f('ix_ibm_cost_tracking_date'), table_name='ibm_cost_tracking')
    op.drop_table('ibm_cost_tracking')
    # ### end Alembic commands ###
