"""empty message

Revision ID: daae9bf3c02d
Revises: 7de3158dd33e
Create Date: 2022-02-25 10:14:29.306919

"""

# revision identifiers, used by Alembic.
revision = 'daae9bf3c02d'
down_revision = '7de3158dd33e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_volume_attachments', sa.Column('id', sa.String(length=32), nullable=True))
    op.add_column('ibm_volume_attachments', sa.Column('zone_id', sa.String(length=32), nullable=False))
    op.add_column('ibm_volume_attachments', sa.Column('region_id', sa.String(length=32), nullable=False))
    op.add_column('ibm_volume_attachments', sa.Column('cloud_id', sa.String(length=32), nullable=False))
    op.create_unique_constraint("id", 'ibm_volume_attachments', ['id'])
    op.create_foreign_key("zone_id", 'ibm_volume_attachments', 'ibm_zones', ['zone_id'], ['id'])
    op.create_foreign_key("region_id", 'ibm_volume_attachments', 'ibm_regions', ['region_id'], ['id'])
    op.create_foreign_key("cloud_id", 'ibm_volume_attachments', 'ibm_clouds', ['cloud_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("cloud_id", 'ibm_volume_attachments', type_='foreignkey')
    op.drop_constraint("region_id", 'ibm_volume_attachments', type_='foreignkey')
    op.drop_constraint("zone_id", 'ibm_volume_attachments', type_='foreignkey')
    op.drop_constraint("id", 'ibm_volume_attachments', type_='unique')
    op.drop_column('ibm_volume_attachments', 'cloud_id')
    op.drop_column('ibm_volume_attachments', 'region_id')
    op.drop_column('ibm_volume_attachments', 'zone_id')
    op.drop_column('ibm_volume_attachments', 'id')
    # ### end Alembic commands ###