"""empty message

Revision ID: de7bca66ed30
Revises: 1c94d3196731
Create Date: 2022-02-15 19:03:34.249863

"""

# revision identifiers, used by Alembic.
revision = 'de7bca66ed30'
down_revision = '1c94d3196731'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_instance_groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('ibm_status', sa.Enum('deleting', 'healthy', 'scaling', 'unhealthy'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('application_port', sa.Integer(), nullable=True),
    sa.Column('membership_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('instance_template_id', sa.String(length=32), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('load_balancer_pool_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['instance_template_id'], ['ibm_instance_templates.id'], ),
    sa.ForeignKeyConstraint(['load_balancer_pool_id'], ['ibm_pools.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', 'cloud_id', name='uix_ibm_instance_group_name_region_id_cloud_id')
    )
    op.create_table('ibm_instance_group_managers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('management_enabled', sa.Boolean(), nullable=False),
    sa.Column('manager_type', sa.Enum('autoscale', 'scheduled'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('instance_group_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instance_group_id'], ['ibm_instance_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'instance_group_id', name='uix_ibm_instance_group_manager_name_instance_group_id')
    )
    op.create_table('ibm_instance_group_memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('delete_instance_on_membership_delete', sa.Boolean(), nullable=False),
    sa.Column('ibm_status', sa.Enum('deleting', 'failed', 'healthy', 'pending', 'unhealthy'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('instance_group_id', sa.String(length=32), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=False),
    sa.Column('instance_template_id', sa.String(length=32), nullable=False),
    sa.Column('pool_member_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['instance_group_id'], ['ibm_instance_groups.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['ibm_instances.id'], ),
    sa.ForeignKeyConstraint(['instance_template_id'], ['ibm_instance_templates.id'], ),
    sa.ForeignKeyConstraint(['pool_member_id'], ['ibm_pool_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'instance_group_id', name='uix_ibm_instance_group_membership_name_instance_group_id')
    )
    op.create_table('ibm_instance_group_manager_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('auto_delete', sa.Boolean(), nullable=False),
    sa.Column('auto_delete_timeout', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('instance_group_manager_action'), nullable=False),
    sa.Column('ibm_status', sa.Enum('active', 'completed', 'failed', 'incompatible', 'omitted'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.Enum('scheduled'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('group_membership_count', sa.Integer(), nullable=True),
    sa.Column('last_applied_at', sa.DateTime(), nullable=True),
    sa.Column('cron_spec', sa.String(length=64), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('max_membership_count', sa.Integer(), nullable=True),
    sa.Column('min_membership_count', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['ibm_instance_group_managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'manager_id', name='uix_ibm_instance_group_manager_action_name_manager_id')
    )
    op.create_table('ibm_instance_group_manager_autoscale_prototypes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('aggregation_window', sa.Integer(), nullable=False),
    sa.Column('cooldown', sa.Integer(), nullable=False),
    sa.Column('max_membership_count', sa.Integer(), nullable=False),
    sa.Column('min_membership_count', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['ibm_instance_group_managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_instance_group_manager_policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metric_type', sa.Enum('cpu', 'memory', 'network_in', 'network_out'), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.Enum('target'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('manager_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['ibm_instance_group_managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'manager_id', name='uix_ibm_instance_group_manager_policy_name_manager_id')
    )
    op.add_column('ibm_subnets', sa.Column('instance_group_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('fk_ibm_subnets_ibm_instance_groups_1', 'ibm_subnets', 'ibm_instance_groups', ['instance_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ibm_subnets_ibm_instance_groups_1', 'ibm_subnets', type_='foreignkey')
    op.drop_column('ibm_subnets', 'instance_group_id')
    op.drop_table('ibm_instance_group_manager_policies')
    op.drop_table('ibm_instance_group_manager_autoscale_prototypes')
    op.drop_table('ibm_instance_group_manager_actions')
    op.drop_table('ibm_instance_group_memberships')
    op.drop_table('ibm_instance_group_managers')
    op.drop_table('ibm_instance_groups')
    # ### end Alembic commands ###