"""empty message

Revision ID: e081ed810d3a
Revises: a4b960476c85
Create Date: 2023-03-14 10:28:03.122386

"""

# revision identifiers, used by Alembic.
revision = 'e081ed810d3a'
down_revision = 'a4b960476c85'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_transit_gateway_connections',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('resource_id', sa.String(length=64), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('network_type', sa.Enum('vpc', 'classic'), nullable=False),
                    sa.Column('network_account_id', sa.String(length=32), nullable=True),
                    sa.Column('prefix_filters_default', sa.Enum('permit', 'deny'), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('transit_gateway_id', sa.String(length=32), nullable=True),
                    sa.Column('cloud_id', sa.String(length=32), nullable=True),
                    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['transit_gateway_id'], ['ibm_transit_gateways.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', 'transit_gateway_id',
                                        name='uix_transit_connection_name_transit_gateway_id')
                    )
    op.create_table('ibm_transit_gateway_route_reports',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('resource_id', sa.String(length=64), nullable=True),
                    sa.Column('connections', sa.JSON(), nullable=False),
                    sa.Column('overlapping_routes', sa.JSON(), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('transit_gateway_id', sa.String(length=32), nullable=True),
                    sa.Column('cloud_id', sa.String(length=32), nullable=True),
                    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['transit_gateway_id'], ['ibm_transit_gateways.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('ibm_transit_gateway_connection_prefix_filters',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('resource_id', sa.String(length=64), nullable=False),
                    sa.Column('action', sa.Enum('permit', 'deny'), nullable=False),
                    sa.Column('prefix', sa.String(length=255), nullable=False),
                    sa.Column('before', sa.String(length=50), nullable=True),
                    sa.Column('ge', sa.Integer(), nullable=True),
                    sa.Column('le', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('connection_id', sa.String(length=32), nullable=True),
                    sa.Column('cloud_id', sa.String(length=32), nullable=True),
                    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['connection_id'], ['ibm_transit_gateway_connections.id'],
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.drop_constraint('fk_ibm_transit_gateways_resource_group_id_ibm_resource_groups', 'ibm_transit_gateways',
                       type_='foreignkey')
    op.create_foreign_key('resource_group_id', 'ibm_transit_gateways', 'ibm_resource_groups', ['resource_group_id'], ['id'],
                          ondelete='CASCADE')
    op.add_column('ibm_vpc_networks', sa.Column('transit_gateway_connection_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('transit_gateway_connection_id', 'ibm_vpc_networks', 'ibm_transit_gateway_connections',
                          ['transit_gateway_connection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transit_gateway_connection_id', 'ibm_vpc_networks', type_='foreignkey')
    op.drop_column('ibm_vpc_networks', 'transit_gateway_connection_id')
    op.drop_constraint('resource_group_id', 'ibm_transit_gateways', type_='foreignkey')
    op.create_foreign_key('fk_ibm_transit_gateways_resource_group_id_ibm_resource_groups', 'ibm_transit_gateways',
                          'ibm_resource_groups', ['resource_group_id'], ['id'], ondelete='SET NULL')

    op.drop_table('ibm_transit_gateway_connection_prefix_filters')
    op.drop_table('ibm_transit_gateway_route_reports')
    op.drop_table('ibm_transit_gateway_connections')
    # ### end Alembic commands ###
