"""empty message

Revision ID: e5aea7db20c4
Revises: 05dbc3c1c8c7
Create Date: 2023-02-15 11:34:29.999610

"""

# revision identifiers, used by Alembic.
revision = 'e5aea7db20c4'
down_revision = '05dbc3c1c8c7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_activity_tracking',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('resource_name', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.String(length=256), nullable=False),
    sa.Column('_detailed_summary', sa.JSON(), nullable=True),
    sa.Column('root_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_activity_tracking')
    # ### end Alembic commands ###