"""empty message

Revision ID: ef01ca0797d0
Revises: 759a50e14fbb
Create Date: 2022-07-18 09:21:08.897071

"""

# revision identifiers, used by Alembic.
revision = 'ef01ca0797d0'
down_revision = '759a50e14fbb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_ssh_keys', 'length',
                    existing_type=sa.Enum('2048', '4096'),
                    type_=mysql.ENUM('1024', "2048", "4096"),
                    existing_nullable=False
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_ssh_keys', 'length',
                    existing_type=mysql.ENUM('1024', "2048", "4096"),
                    type_=sa.Enum("2048", "4096"),
                    )
    # ### end Alembic commands ###
