"""empty message
Revision ID: f43d800444ba
Revises: 6207c39472fe
Create Date: 2022-09-29 07:10:02.698215
"""

# revision identifiers, used by Alembic.
revision = 'f43d800444ba'
down_revision = '6207c39472fe'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disaster_recovery_resource_blueprints', sa.Column('description', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disaster_recovery_resource_blueprints', 'description')
    # ### end Alembic commands ###
