"""empty message

Revision ID: f876524fb5ff
Revises: de7bca66ed30
Create Date: 2022-02-16 12:03:31.075497

"""

# revision identifiers, used by Alembic.
revision = 'f876524fb5ff'
down_revision = 'de7bca66ed30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_service_credential_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('guid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('reader', 'writer', 'manager', 'content_reader', 'object_writer', 'object_manager'),
              nullable=False),
    sa.Column('iam_role_crn', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('migrated', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('is_hmac', sa.Boolean(), nullable=False),
    sa.Column('access_key_id', sa.String(length=255), nullable=True),
    sa.Column('secret_access_key', sa.String(length=255), nullable=True),
    sa.Column('iam_service_id_crn', sa.String(length=255), nullable=True),
    sa.Column('cloud_object_storage_id', sa.String(length=32), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_object_storage_id'], ['ibm_cloud_object_storages.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_service_credential_keys')
    # ### end Alembic commands ###