"""empty message

Revision ID: fb1009b64a8a
Revises: d8fafc7cf1d1
Create Date: 2021-09-23 18:48:20.012197

"""

# revision identifiers, used by Alembic.
revision = 'fb1009b64a8a'
down_revision = 'd8fafc7cf1d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_address_prefixes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('cidr', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('has_subnets', sa.Boolean(), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['ibm_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'vpc_id', name='uix_ibm_address_prefix_name_vpc_id')
    )
    op.create_table('ibm_network_acls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', 'vpc_id', 'cloud_id', name='uix_ibm_acl_name_vpc_region_id_cloud_id')
    )
    op.create_table('ibm_network_acl_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.Enum('allow', 'deny'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound'), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('ip_version', sa.Enum('ipv4', 'ipv6'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('tcp_udp_dst_port_max', sa.Integer(), nullable=True),
    sa.Column('tcp_udp_dst_port_min', sa.Integer(), nullable=True),
    sa.Column('tcp_udp_src_port_max', sa.Integer(), nullable=True),
    sa.Column('tcp_udp_src_port_min', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('icmp_code', sa.Integer(), nullable=True),
    sa.Column('icmp_type', sa.Integer(), nullable=True),
    sa.Column('before_id', sa.String(length=32), nullable=True),
    sa.Column('acl_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['acl_id'], ['ibm_network_acls.id'], ),
    sa.ForeignKeyConstraint(['before_id'], ['ibm_network_acl_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'acl_id', name='uix_ibm_acl_name_acl_id')
    )
    op.create_table('ibm_public_gateways',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=255), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('ibm_status', sa.Enum('available', 'failed', 'pending', 'deleting'), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['ibm_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'vpc_id', 'cloud_id', 'region_id', name='uix_ibm_public_gateway_name_vpc_region_id_cloud_id')
    )
    op.create_table('ibm_routing_tables',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('stable', 'deleting', 'failed', 'pending', 'waiting', 'suspended', 'updating'), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('route_direct_link_ingress', sa.Boolean(), nullable=False),
    sa.Column('route_transit_gateway_ingress', sa.Boolean(), nullable=False),
    sa.Column('route_vpc_zone_ingress', sa.Boolean(), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'vpc_id', 'region_id', name='uix_ibm_routing_table_name_vpc_id_region_id')
    )
    op.create_table('ibm_routing_table_routes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting', 'suspended'), nullable=False),
    sa.Column('destination', sa.String(length=32), nullable=False),
    sa.Column('next_hop_address_ip', sa.String(length=16), nullable=True),
    sa.Column('routing_table_id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['routing_table_id'], ['ibm_routing_tables.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['ibm_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'routing_table_id', name='uix_ibm_route_name_routing_table_id')
    )
    op.create_table('ibm_floating_ips',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ibm_status', sa.Enum('available', 'deleting', 'failed', 'pending'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('public_gateway_id', sa.String(length=32), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['public_gateway_id'], ['ibm_public_gateways.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['ibm_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region_id', 'cloud_id', name='uix_ibm_floating_ip_name_region_id_cloud_id')
    )
    op.create_table('ibm_subnets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('crn', sa.Text(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ibm_status', sa.Enum('available', 'deleting', 'pending', 'failed'), nullable=False),
    sa.Column('available_ipv4_address_count', sa.BigInteger(), nullable=False),
    sa.Column('total_ipv4_address_count', sa.BigInteger(), nullable=False),
    sa.Column('ip_version', sa.Enum('ipv4'), nullable=False),
    sa.Column('ipv4_cidr_block', sa.String(length=255), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('network_acl_id', sa.String(length=32), nullable=True),
    sa.Column('public_gateway_id', sa.String(length=32), nullable=True),
    sa.Column('address_prefix_id', sa.String(length=32), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('routing_table_id', sa.String(length=32), nullable=True),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['address_prefix_id'], ['ibm_address_prefixes.id'], ),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['network_acl_id'], ['ibm_network_acls.id'], ),
    sa.ForeignKeyConstraint(['public_gateway_id'], ['ibm_public_gateways.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ibm_regions.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['routing_table_id'], ['ibm_routing_tables.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['ibm_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cloud_id', 'vpc_id', 'region_id', name='uix_ibm_subnet_name_cloud_id_vpc_id_region_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_subnets')
    op.drop_table('ibm_floating_ips')
    op.drop_table('ibm_routing_table_routes')
    op.drop_table('ibm_routing_tables')
    op.drop_table('ibm_public_gateways')
    op.drop_table('ibm_network_acl_rules')
    op.drop_table('ibm_network_acls')
    op.drop_table('ibm_address_prefixes')
    # ### end Alembic commands ###
