"""empty message

Revision ID: fc24da342add
Revises: 2e021ba9f5f2
Create Date: 2022-01-07 16:52:15.024752

"""

# revision identifiers, used by Alembic.
revision = 'fc24da342add'
down_revision = '2e021ba9f5f2'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_placement_groups', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('ibm_placement_groups', 'strategy',
                    existing_type=sa.Enum('placement_group'),
                    type_=sa.Enum('host_spread', 'power_spread'),
                    nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_placement_groups', 'strategy',
                    existing_type=sa.Enum('host_spread', 'power_spread'),
                    nullable=True, type_=sa.Enum('placement_group'))
    op.drop_column('ibm_placement_groups', 'status')
    # ### end Alembic commands ###
