"""empty message

Revision ID: feac18492e5a
Revises: 69127e238371
Create Date: 2021-11-11 04:28:16.881667

"""

# revision identifiers, used by Alembic.
revision = 'feac18492e5a'
down_revision = '69127e238371'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_public_gateways', 'created_at',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('ibm_floating_ips', 'resource_group_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_floating_ips', 'resource_group_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('ibm_public_gateways', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
