# coding: utf-8

# flake8: noqa
"""
    Consumption

    Keeps track of the different services being utilized by users  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from consumption_client.models.consumption import Consumption
from consumption_client.models.consumption_view import ConsumptionView
from consumption_client.models.error import Error
