VPC_MAJOR_VERSION = "v1"
VPC_DATE_BASED_VERSION = "2022-04-07"
VPC_GENERATION = "2"
VPC_RESOURCE_REQUIRED_PARAMS = {
    "version": VPC_DATE_BASED_VERSION,
    "generation": VPC_GENERATION
}
VPC_DEFAULT_REGION = "us-south"
VPC_DEFAULT_PAGINATION_LIMIT = 100

RESOURCE_MANAGER_MAJOR_VERSION = "v2"
RESOURCE_CONTROLLER_VERSION = "v2"
GLOBAL_CATALOG_VERSION = "v1"
PRIVATE_CATALOG_VERSION = "v1-beta"
GLOBAL_SEARCH_VERSION = "v2"

TRANSIT_GATEWAY_VERSION = "/v1/"
TRANSIT_GATEWAY_DEFAULT_PAGINATION_LIMIT = 50

TRANSIT_GATEWAY_PARAMS = {
    "version": "2022-08-22"
}
GLOBAL_TAG_VERSION = "v1"
